// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="snn_inference_profile_hls_snn_inference_profile_hls,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.653000,HLS_SYN_LAT=65539,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=897,HLS_SYN_LUT=1624,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_inference_profile_hls (
        ap_clk,
        ap_rst_n,
        s_axis_spikes_TDATA,
        s_axis_spikes_TVALID,
        s_axis_spikes_TREADY,
        s_axis_spikes_TKEEP,
        s_axis_spikes_TSTRB,
        s_axis_spikes_TUSER,
        s_axis_spikes_TLAST,
        s_axis_spikes_TID,
        s_axis_spikes_TDEST,
        m_axis_spikes_TDATA,
        m_axis_spikes_TVALID,
        m_axis_spikes_TREADY,
        m_axis_spikes_TKEEP,
        m_axis_spikes_TSTRB,
        m_axis_spikes_TUSER,
        m_axis_spikes_TLAST,
        m_axis_spikes_TID,
        m_axis_spikes_TDEST,
        spike_in_valid,
        spike_in_neuron_id,
        spike_in_weight,
        spike_in_ready,
        spike_out_valid,
        spike_out_neuron_id,
        spike_out_weight,
        spike_out_ready,
        snn_enable,
        snn_reset,
        threshold_out,
        leak_rate_out,
        snn_ready,
        snn_busy,
        s_axi_ctrl_AWVALID,
        s_axi_ctrl_AWREADY,
        s_axi_ctrl_AWADDR,
        s_axi_ctrl_WVALID,
        s_axi_ctrl_WREADY,
        s_axi_ctrl_WDATA,
        s_axi_ctrl_WSTRB,
        s_axi_ctrl_ARVALID,
        s_axi_ctrl_ARREADY,
        s_axi_ctrl_ARADDR,
        s_axi_ctrl_RVALID,
        s_axi_ctrl_RREADY,
        s_axi_ctrl_RDATA,
        s_axi_ctrl_RRESP,
        s_axi_ctrl_BVALID,
        s_axi_ctrl_BREADY,
        s_axi_ctrl_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 8;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] s_axis_spikes_TDATA;
input   s_axis_spikes_TVALID;
output   s_axis_spikes_TREADY;
input  [3:0] s_axis_spikes_TKEEP;
input  [3:0] s_axis_spikes_TSTRB;
input  [0:0] s_axis_spikes_TUSER;
input  [0:0] s_axis_spikes_TLAST;
input  [0:0] s_axis_spikes_TID;
input  [0:0] s_axis_spikes_TDEST;
output  [31:0] m_axis_spikes_TDATA;
output   m_axis_spikes_TVALID;
input   m_axis_spikes_TREADY;
output  [3:0] m_axis_spikes_TKEEP;
output  [3:0] m_axis_spikes_TSTRB;
output  [0:0] m_axis_spikes_TUSER;
output  [0:0] m_axis_spikes_TLAST;
output  [0:0] m_axis_spikes_TID;
output  [0:0] m_axis_spikes_TDEST;
output  [0:0] spike_in_valid;
output  [10:0] spike_in_neuron_id;
output  [7:0] spike_in_weight;
input  [0:0] spike_in_ready;
input  [0:0] spike_out_valid;
input  [10:0] spike_out_neuron_id;
input  [7:0] spike_out_weight;
output  [0:0] spike_out_ready;
output  [0:0] snn_enable;
output  [0:0] snn_reset;
output  [15:0] threshold_out;
output  [15:0] leak_rate_out;
input  [0:0] snn_ready;
input  [0:0] snn_busy;
input   s_axi_ctrl_AWVALID;
output   s_axi_ctrl_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_AWADDR;
input   s_axi_ctrl_WVALID;
output   s_axi_ctrl_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_ctrl_WSTRB;
input   s_axi_ctrl_ARVALID;
output   s_axi_ctrl_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_ARADDR;
output   s_axi_ctrl_RVALID;
input   s_axi_ctrl_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_RDATA;
output  [1:0] s_axi_ctrl_RRESP;
output   s_axi_ctrl_BVALID;
input   s_axi_ctrl_BREADY;
output  [1:0] s_axi_ctrl_BRESP;
output   interrupt;

reg[0:0] snn_enable;
reg[0:0] snn_reset;
reg[15:0] threshold_out;
reg[15:0] leak_rate_out;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] ctrl_reg;
wire   [31:0] config_reg;
wire   [31:0] mode_reg;
wire   [31:0] time_steps_reg;
wire   [143:0] learning_params;
wire   [79:0] encoder_config;
wire   [31:0] status_reg;
reg    status_reg_ap_vld;
reg    spike_count_reg_ap_vld;
reg    weight_sum_reg_ap_vld;
reg    version_reg_ap_vld;
wire   [7:0] reward_signal;
reg   [31:0] timestamp;
reg   [31:0] spike_counter;
reg   [0:0] first_spike_sent;
reg   [0:0] first_spike_pending;
reg   [10:0] first_spike_pending_id;
reg   [7:0] first_spike_pending_weight;
reg   [0:0] spike_in_valid_toggle;
reg   [0:0] spike_out_ack_toggle;
reg   [0:0] snn_busy_read_reg_677;
reg   [0:0] snn_ready_read_reg_682;
reg   [7:0] spike_out_weight_read_reg_687;
reg   [10:0] spike_out_neuron_id_read_reg_692;
reg   [0:0] spike_out_valid_read_reg_698;
reg   [0:0] spike_in_ready_read_reg_703;
reg   [31:0] mode_reg_read_reg_708;
wire   [0:0] enable_fu_425_p1;
reg   [0:0] enable_reg_737;
reg   [0:0] first_spike_only_reg_749;
wire   [15:0] time_steps_1_fu_465_p3;
reg   [15:0] time_steps_1_reg_756;
wire   [0:0] or_ln129_fu_575_p2;
reg   [0:0] or_ln129_reg_762;
wire    ap_CS_fsm_state2;
wire   [0:0] or_ln143_fu_587_p2;
reg   [0:0] or_ln143_reg_767;
wire   [0:0] or_ln161_fu_599_p2;
reg   [0:0] or_ln161_reg_772;
wire   [0:0] icmp_ln122_fu_606_p2;
reg   [0:0] icmp_ln122_reg_777;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_done;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_idle;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_ready;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TREADY;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_s_axis_spikes_TREADY;
wire   [31:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDATA;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID;
wire   [3:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TKEEP;
wire   [3:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TSTRB;
wire   [0:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TUSER;
wire   [0:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TLAST;
wire   [0:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TID;
wire   [0:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDEST;
wire   [0:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05525_phi_out;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05525_phi_out_ap_vld;
wire   [7:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi_out;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi_out_ap_vld;
wire   [10:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi4_out;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi4_out_ap_vld;
wire   [0:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05623_phi_out;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05623_phi_out_ap_vld;
wire   [0:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_out_ack_toggle_o;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_out_ack_toggle_o_ap_vld;
wire   [0:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_in_valid_toggle_o;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_in_valid_toggle_o_ap_vld;
wire   [31:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_counter_o;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_counter_o_ap_vld;
wire   [0:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_o;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_o_ap_vld;
wire   [10:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_id_o;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_id_o_ap_vld;
wire   [7:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_weight_o;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_weight_o_ap_vld;
wire   [31:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_timestamp_o;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_timestamp_o_ap_vld;
wire   [0:0] grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_sent_o;
wire    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_sent_o_ap_vld;
reg    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [31:0] m_axis_spikes_TDATA_reg;
reg   [3:0] m_axis_spikes_TKEEP_reg;
reg   [3:0] m_axis_spikes_TSTRB_reg;
reg   [0:0] m_axis_spikes_TUSER_reg;
reg   [0:0] m_axis_spikes_TLAST_reg;
reg   [0:0] m_axis_spikes_TID_reg;
reg   [0:0] m_axis_spikes_TDEST_reg;
wire   [0:0] reset_fu_430_p3;
wire   [0:0] clear_counters_fu_439_p3;
wire    ap_CS_fsm_state4;
reg   [0:0] snn_enable_preg;
reg   [0:0] snn_reset_preg;
wire   [15:0] trunc_ln119_fu_551_p1;
reg   [15:0] threshold_out_preg;
reg   [15:0] leak_rate_out_preg;
wire    regslice_both_m_axis_spikes_V_data_V_U_apdone_blk;
wire   [0:0] icmp_ln87_fu_455_p2;
wire   [15:0] time_steps_fu_461_p1;
wire   [0:0] xor_ln129_fu_565_p2;
wire   [0:0] xor_ln129_1_fu_570_p2;
wire   [0:0] xor_ln143_fu_582_p2;
wire   [0:0] xor_ln161_fu_594_p2;
wire   [1:0] tmp_9_fu_627_p3;
wire   [2:0] zext_ln205_fu_633_p1;
wire   [3:0] tmp_s_fu_640_p3;
wire   [1:0] trunc_ln206_fu_637_p1;
wire   [5:0] zext_ln206_fu_647_p1;
wire   [16:0] status_fu_655_p5;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    regslice_both_s_axis_spikes_V_data_V_U_apdone_blk;
wire   [31:0] s_axis_spikes_TDATA_int_regslice;
wire    s_axis_spikes_TVALID_int_regslice;
reg    s_axis_spikes_TREADY_int_regslice;
wire    regslice_both_s_axis_spikes_V_data_V_U_ack_in;
wire    regslice_both_s_axis_spikes_V_keep_V_U_apdone_blk;
wire   [3:0] s_axis_spikes_TKEEP_int_regslice;
wire    regslice_both_s_axis_spikes_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_spikes_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_spikes_V_strb_V_U_apdone_blk;
wire   [3:0] s_axis_spikes_TSTRB_int_regslice;
wire    regslice_both_s_axis_spikes_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_spikes_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_spikes_V_user_V_U_apdone_blk;
wire   [0:0] s_axis_spikes_TUSER_int_regslice;
wire    regslice_both_s_axis_spikes_V_user_V_U_vld_out;
wire    regslice_both_s_axis_spikes_V_user_V_U_ack_in;
wire    regslice_both_s_axis_spikes_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_spikes_TLAST_int_regslice;
wire    regslice_both_s_axis_spikes_V_last_V_U_vld_out;
wire    regslice_both_s_axis_spikes_V_last_V_U_ack_in;
wire    regslice_both_s_axis_spikes_V_id_V_U_apdone_blk;
wire   [0:0] s_axis_spikes_TID_int_regslice;
wire    regslice_both_s_axis_spikes_V_id_V_U_vld_out;
wire    regslice_both_s_axis_spikes_V_id_V_U_ack_in;
wire    regslice_both_s_axis_spikes_V_dest_V_U_apdone_blk;
wire   [0:0] s_axis_spikes_TDEST_int_regslice;
wire    regslice_both_s_axis_spikes_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_spikes_V_dest_V_U_ack_in;
reg   [31:0] m_axis_spikes_TDATA_int_regslice;
wire    m_axis_spikes_TVALID_int_regslice;
wire    m_axis_spikes_TREADY_int_regslice;
wire    regslice_both_m_axis_spikes_V_data_V_U_vld_out;
wire    regslice_both_m_axis_spikes_V_keep_V_U_apdone_blk;
reg   [3:0] m_axis_spikes_TKEEP_int_regslice;
wire    regslice_both_m_axis_spikes_V_keep_V_U_ack_in_dummy;
wire    regslice_both_m_axis_spikes_V_keep_V_U_vld_out;
wire    regslice_both_m_axis_spikes_V_strb_V_U_apdone_blk;
reg   [3:0] m_axis_spikes_TSTRB_int_regslice;
wire    regslice_both_m_axis_spikes_V_strb_V_U_ack_in_dummy;
wire    regslice_both_m_axis_spikes_V_strb_V_U_vld_out;
wire    regslice_both_m_axis_spikes_V_user_V_U_apdone_blk;
reg   [0:0] m_axis_spikes_TUSER_int_regslice;
wire    regslice_both_m_axis_spikes_V_user_V_U_ack_in_dummy;
wire    regslice_both_m_axis_spikes_V_user_V_U_vld_out;
wire    regslice_both_m_axis_spikes_V_last_V_U_apdone_blk;
reg   [0:0] m_axis_spikes_TLAST_int_regslice;
wire    regslice_both_m_axis_spikes_V_last_V_U_ack_in_dummy;
wire    regslice_both_m_axis_spikes_V_last_V_U_vld_out;
wire    regslice_both_m_axis_spikes_V_id_V_U_apdone_blk;
reg   [0:0] m_axis_spikes_TID_int_regslice;
wire    regslice_both_m_axis_spikes_V_id_V_U_ack_in_dummy;
wire    regslice_both_m_axis_spikes_V_id_V_U_vld_out;
wire    regslice_both_m_axis_spikes_V_dest_V_U_apdone_blk;
reg   [0:0] m_axis_spikes_TDEST_int_regslice;
wire    regslice_both_m_axis_spikes_V_dest_V_U_ack_in_dummy;
wire    regslice_both_m_axis_spikes_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 timestamp = 32'd0;
#0 spike_counter = 32'd0;
#0 first_spike_sent = 1'd0;
#0 first_spike_pending = 1'd0;
#0 first_spike_pending_id = 11'd0;
#0 first_spike_pending_weight = 8'd0;
#0 spike_in_valid_toggle = 1'd0;
#0 spike_out_ack_toggle = 1'd0;
#0 grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start_reg = 1'b0;
#0 snn_enable_preg = 1'd0;
#0 snn_reset_preg = 1'd0;
#0 threshold_out_preg = 16'd0;
#0 leak_rate_out_preg = 16'd0;
end

snn_inference_profile_hls_snn_inference_profile_hls_Pipeline_TIME_LOOP grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start),
    .ap_done(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_done),
    .ap_idle(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_idle),
    .ap_ready(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_ready),
    .m_axis_spikes_TREADY(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TREADY),
    .s_axis_spikes_TVALID(s_axis_spikes_TVALID_int_regslice),
    .time_steps_1(time_steps_1_reg_756),
    .empty_21(enable_reg_737),
    .or_ln161(or_ln161_reg_772),
    .or_ln143(or_ln143_reg_767),
    .or_ln129(or_ln129_reg_762),
    .s_axis_spikes_TDATA(s_axis_spikes_TDATA_int_regslice),
    .s_axis_spikes_TREADY(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_s_axis_spikes_TREADY),
    .s_axis_spikes_TKEEP(s_axis_spikes_TKEEP_int_regslice),
    .s_axis_spikes_TSTRB(s_axis_spikes_TSTRB_int_regslice),
    .s_axis_spikes_TUSER(s_axis_spikes_TUSER_int_regslice),
    .s_axis_spikes_TLAST(s_axis_spikes_TLAST_int_regslice),
    .s_axis_spikes_TID(s_axis_spikes_TID_int_regslice),
    .s_axis_spikes_TDEST(s_axis_spikes_TDEST_int_regslice),
    .m_axis_spikes_TDATA(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDATA),
    .m_axis_spikes_TVALID(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID),
    .m_axis_spikes_TKEEP(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TKEEP),
    .m_axis_spikes_TSTRB(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TSTRB),
    .m_axis_spikes_TUSER(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TUSER),
    .m_axis_spikes_TLAST(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TLAST),
    .m_axis_spikes_TID(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TID),
    .m_axis_spikes_TDEST(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDEST),
    .empty(first_spike_only_reg_749),
    .spike_out_weight(spike_out_weight_read_reg_687),
    .zext_ln162(spike_out_neuron_id_read_reg_692),
    .spike_out_neuron_id(spike_out_neuron_id_read_reg_692),
    .p_0_0_05525_phi_out(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05525_phi_out),
    .p_0_0_05525_phi_out_ap_vld(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05525_phi_out_ap_vld),
    .p_phi_out(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi_out),
    .p_phi_out_ap_vld(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi_out_ap_vld),
    .p_phi4_out(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi4_out),
    .p_phi4_out_ap_vld(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi4_out_ap_vld),
    .p_0_0_05623_phi_out(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05623_phi_out),
    .p_0_0_05623_phi_out_ap_vld(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05623_phi_out_ap_vld),
    .spike_out_ack_toggle_i(spike_out_ack_toggle),
    .spike_out_ack_toggle_o(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_out_ack_toggle_o),
    .spike_out_ack_toggle_o_ap_vld(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_out_ack_toggle_o_ap_vld),
    .spike_in_valid_toggle_i(spike_in_valid_toggle),
    .spike_in_valid_toggle_o(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_in_valid_toggle_o),
    .spike_in_valid_toggle_o_ap_vld(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_in_valid_toggle_o_ap_vld),
    .spike_counter_i(spike_counter),
    .spike_counter_o(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_counter_o),
    .spike_counter_o_ap_vld(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_counter_o_ap_vld),
    .first_spike_pending_i(first_spike_pending),
    .first_spike_pending_o(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_o),
    .first_spike_pending_o_ap_vld(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_o_ap_vld),
    .first_spike_pending_id_i(first_spike_pending_id),
    .first_spike_pending_id_o(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_id_o),
    .first_spike_pending_id_o_ap_vld(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_id_o_ap_vld),
    .first_spike_pending_weight_i(first_spike_pending_weight),
    .first_spike_pending_weight_o(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_weight_o),
    .first_spike_pending_weight_o_ap_vld(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_weight_o_ap_vld),
    .timestamp_i(timestamp),
    .timestamp_o(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_timestamp_o),
    .timestamp_o_ap_vld(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_timestamp_o_ap_vld),
    .first_spike_sent_i(first_spike_sent),
    .first_spike_sent_o(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_sent_o),
    .first_spike_sent_o_ap_vld(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_sent_o_ap_vld)
);

snn_inference_profile_hls_ctrl_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
ctrl_s_axi_U(
    .AWVALID(s_axi_ctrl_AWVALID),
    .AWREADY(s_axi_ctrl_AWREADY),
    .AWADDR(s_axi_ctrl_AWADDR),
    .WVALID(s_axi_ctrl_WVALID),
    .WREADY(s_axi_ctrl_WREADY),
    .WDATA(s_axi_ctrl_WDATA),
    .WSTRB(s_axi_ctrl_WSTRB),
    .ARVALID(s_axi_ctrl_ARVALID),
    .ARREADY(s_axi_ctrl_ARREADY),
    .ARADDR(s_axi_ctrl_ARADDR),
    .RVALID(s_axi_ctrl_RVALID),
    .RREADY(s_axi_ctrl_RREADY),
    .RDATA(s_axi_ctrl_RDATA),
    .RRESP(s_axi_ctrl_RRESP),
    .BVALID(s_axi_ctrl_BVALID),
    .BREADY(s_axi_ctrl_BREADY),
    .BRESP(s_axi_ctrl_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ctrl_reg(ctrl_reg),
    .config_reg(config_reg),
    .mode_reg(mode_reg),
    .time_steps_reg(time_steps_reg),
    .learning_params(learning_params),
    .encoder_config(encoder_config),
    .status_reg(status_reg),
    .status_reg_ap_vld(status_reg_ap_vld),
    .spike_count_reg(spike_counter),
    .spike_count_reg_ap_vld(spike_count_reg_ap_vld),
    .weight_sum_reg(32'd0),
    .weight_sum_reg_ap_vld(weight_sum_reg_ap_vld),
    .version_reg(32'd539361825),
    .version_reg_ap_vld(version_reg_ap_vld),
    .reward_signal(reward_signal),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

snn_inference_profile_hls_regslice_both #(
    .DataWidth( 32 ))
regslice_both_s_axis_spikes_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_spikes_TDATA),
    .vld_in(s_axis_spikes_TVALID),
    .ack_in(regslice_both_s_axis_spikes_V_data_V_U_ack_in),
    .data_out(s_axis_spikes_TDATA_int_regslice),
    .vld_out(s_axis_spikes_TVALID_int_regslice),
    .ack_out(s_axis_spikes_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_spikes_V_data_V_U_apdone_blk)
);

snn_inference_profile_hls_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_axis_spikes_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_spikes_TKEEP),
    .vld_in(s_axis_spikes_TVALID),
    .ack_in(regslice_both_s_axis_spikes_V_keep_V_U_ack_in),
    .data_out(s_axis_spikes_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_spikes_V_keep_V_U_vld_out),
    .ack_out(s_axis_spikes_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_spikes_V_keep_V_U_apdone_blk)
);

snn_inference_profile_hls_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_axis_spikes_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_spikes_TSTRB),
    .vld_in(s_axis_spikes_TVALID),
    .ack_in(regslice_both_s_axis_spikes_V_strb_V_U_ack_in),
    .data_out(s_axis_spikes_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_spikes_V_strb_V_U_vld_out),
    .ack_out(s_axis_spikes_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_spikes_V_strb_V_U_apdone_blk)
);

snn_inference_profile_hls_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_spikes_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_spikes_TUSER),
    .vld_in(s_axis_spikes_TVALID),
    .ack_in(regslice_both_s_axis_spikes_V_user_V_U_ack_in),
    .data_out(s_axis_spikes_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_spikes_V_user_V_U_vld_out),
    .ack_out(s_axis_spikes_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_spikes_V_user_V_U_apdone_blk)
);

snn_inference_profile_hls_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_spikes_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_spikes_TLAST),
    .vld_in(s_axis_spikes_TVALID),
    .ack_in(regslice_both_s_axis_spikes_V_last_V_U_ack_in),
    .data_out(s_axis_spikes_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_spikes_V_last_V_U_vld_out),
    .ack_out(s_axis_spikes_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_spikes_V_last_V_U_apdone_blk)
);

snn_inference_profile_hls_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_spikes_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_spikes_TID),
    .vld_in(s_axis_spikes_TVALID),
    .ack_in(regslice_both_s_axis_spikes_V_id_V_U_ack_in),
    .data_out(s_axis_spikes_TID_int_regslice),
    .vld_out(regslice_both_s_axis_spikes_V_id_V_U_vld_out),
    .ack_out(s_axis_spikes_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_spikes_V_id_V_U_apdone_blk)
);

snn_inference_profile_hls_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_spikes_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_spikes_TDEST),
    .vld_in(s_axis_spikes_TVALID),
    .ack_in(regslice_both_s_axis_spikes_V_dest_V_U_ack_in),
    .data_out(s_axis_spikes_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_spikes_V_dest_V_U_vld_out),
    .ack_out(s_axis_spikes_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_spikes_V_dest_V_U_apdone_blk)
);

snn_inference_profile_hls_regslice_both #(
    .DataWidth( 32 ))
regslice_both_m_axis_spikes_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_spikes_TDATA_int_regslice),
    .vld_in(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID),
    .ack_in(m_axis_spikes_TREADY_int_regslice),
    .data_out(m_axis_spikes_TDATA),
    .vld_out(regslice_both_m_axis_spikes_V_data_V_U_vld_out),
    .ack_out(m_axis_spikes_TREADY),
    .apdone_blk(regslice_both_m_axis_spikes_V_data_V_U_apdone_blk)
);

snn_inference_profile_hls_regslice_both #(
    .DataWidth( 4 ))
regslice_both_m_axis_spikes_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_spikes_TKEEP_int_regslice),
    .vld_in(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID),
    .ack_in(regslice_both_m_axis_spikes_V_keep_V_U_ack_in_dummy),
    .data_out(m_axis_spikes_TKEEP),
    .vld_out(regslice_both_m_axis_spikes_V_keep_V_U_vld_out),
    .ack_out(m_axis_spikes_TREADY),
    .apdone_blk(regslice_both_m_axis_spikes_V_keep_V_U_apdone_blk)
);

snn_inference_profile_hls_regslice_both #(
    .DataWidth( 4 ))
regslice_both_m_axis_spikes_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_spikes_TSTRB_int_regslice),
    .vld_in(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID),
    .ack_in(regslice_both_m_axis_spikes_V_strb_V_U_ack_in_dummy),
    .data_out(m_axis_spikes_TSTRB),
    .vld_out(regslice_both_m_axis_spikes_V_strb_V_U_vld_out),
    .ack_out(m_axis_spikes_TREADY),
    .apdone_blk(regslice_both_m_axis_spikes_V_strb_V_U_apdone_blk)
);

snn_inference_profile_hls_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_spikes_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_spikes_TUSER_int_regslice),
    .vld_in(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID),
    .ack_in(regslice_both_m_axis_spikes_V_user_V_U_ack_in_dummy),
    .data_out(m_axis_spikes_TUSER),
    .vld_out(regslice_both_m_axis_spikes_V_user_V_U_vld_out),
    .ack_out(m_axis_spikes_TREADY),
    .apdone_blk(regslice_both_m_axis_spikes_V_user_V_U_apdone_blk)
);

snn_inference_profile_hls_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_spikes_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_spikes_TLAST_int_regslice),
    .vld_in(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID),
    .ack_in(regslice_both_m_axis_spikes_V_last_V_U_ack_in_dummy),
    .data_out(m_axis_spikes_TLAST),
    .vld_out(regslice_both_m_axis_spikes_V_last_V_U_vld_out),
    .ack_out(m_axis_spikes_TREADY),
    .apdone_blk(regslice_both_m_axis_spikes_V_last_V_U_apdone_blk)
);

snn_inference_profile_hls_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_spikes_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_spikes_TID_int_regslice),
    .vld_in(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID),
    .ack_in(regslice_both_m_axis_spikes_V_id_V_U_ack_in_dummy),
    .data_out(m_axis_spikes_TID),
    .vld_out(regslice_both_m_axis_spikes_V_id_V_U_vld_out),
    .ack_out(m_axis_spikes_TREADY),
    .apdone_blk(regslice_both_m_axis_spikes_V_id_V_U_apdone_blk)
);

snn_inference_profile_hls_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_spikes_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_spikes_TDEST_int_regslice),
    .vld_in(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID),
    .ack_in(regslice_both_m_axis_spikes_V_dest_V_U_ack_in_dummy),
    .data_out(m_axis_spikes_TDEST),
    .vld_out(regslice_both_m_axis_spikes_V_dest_V_U_vld_out),
    .ack_out(m_axis_spikes_TREADY),
    .apdone_blk(regslice_both_m_axis_spikes_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start_reg <= 1'b1;
        end else if ((grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_ready == 1'b1)) begin
            grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        leak_rate_out_preg <= 16'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            leak_rate_out_preg <= {{config_reg[31:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        snn_enable_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            snn_enable_preg <= enable_fu_425_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        snn_reset_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            snn_reset_preg <= ctrl_reg[32'd1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        threshold_out_preg <= 16'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            threshold_out_preg <= trunc_ln119_fu_551_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((enable_fu_425_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((reset_fu_430_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        first_spike_pending <= 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_o_ap_vld == 1'b1))) begin
        first_spike_pending <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((enable_fu_425_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((reset_fu_430_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        first_spike_pending_id <= 11'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_id_o_ap_vld == 1'b1))) begin
        first_spike_pending_id <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_id_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((enable_fu_425_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((reset_fu_430_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        first_spike_pending_weight <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_weight_o_ap_vld == 1'b1))) begin
        first_spike_pending_weight <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_weight_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((enable_fu_425_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((reset_fu_430_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        first_spike_sent <= 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_sent_o_ap_vld == 1'b1))) begin
        first_spike_sent <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_sent_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((clear_counters_fu_439_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((reset_fu_430_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        spike_counter <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_counter_o_ap_vld == 1'b1))) begin
        spike_counter <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_counter_o;
    end
end

always @ (posedge ap_clk) begin
    if (((reset_fu_430_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        spike_in_valid_toggle <= 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_in_valid_toggle_o_ap_vld == 1'b1))) begin
        spike_in_valid_toggle <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_in_valid_toggle_o;
    end
end

always @ (posedge ap_clk) begin
    if (((reset_fu_430_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        spike_out_ack_toggle <= 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_out_ack_toggle_o_ap_vld == 1'b1))) begin
        spike_out_ack_toggle <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_out_ack_toggle_o;
    end
end

always @ (posedge ap_clk) begin
    if (((reset_fu_430_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        timestamp <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_timestamp_o_ap_vld == 1'b1))) begin
        timestamp <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_timestamp_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        enable_reg_737 <= enable_fu_425_p1;
        first_spike_only_reg_749 <= ctrl_reg[32'd7];
        mode_reg_read_reg_708 <= mode_reg;
        snn_busy_read_reg_677 <= snn_busy;
        snn_ready_read_reg_682 <= snn_ready;
        spike_in_ready_read_reg_703 <= spike_in_ready;
        spike_out_neuron_id_read_reg_692 <= spike_out_neuron_id;
        spike_out_valid_read_reg_698 <= spike_out_valid;
        spike_out_weight_read_reg_687 <= spike_out_weight;
        time_steps_1_reg_756 <= time_steps_1_fu_465_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln122_reg_777 <= icmp_ln122_fu_606_p2;
        or_ln129_reg_762 <= or_ln129_fu_575_p2;
        or_ln143_reg_767 <= or_ln143_fu_587_p2;
        or_ln161_reg_772 <= or_ln161_fu_599_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID == 1'b1))) begin
        m_axis_spikes_TDATA_reg <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDATA;
        m_axis_spikes_TDEST_reg <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDEST;
        m_axis_spikes_TID_reg <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TID;
        m_axis_spikes_TKEEP_reg <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TKEEP;
        m_axis_spikes_TLAST_reg <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TLAST;
        m_axis_spikes_TSTRB_reg <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TSTRB;
        m_axis_spikes_TUSER_reg <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TUSER;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_m_axis_spikes_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_m_axis_spikes_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_m_axis_spikes_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        leak_rate_out = {{config_reg[31:16]}};
    end else begin
        leak_rate_out = leak_rate_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID == 1'b1))) begin
        m_axis_spikes_TDATA_int_regslice = grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDATA;
    end else begin
        m_axis_spikes_TDATA_int_regslice = m_axis_spikes_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID == 1'b1))) begin
        m_axis_spikes_TDEST_int_regslice = grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDEST;
    end else begin
        m_axis_spikes_TDEST_int_regslice = m_axis_spikes_TDEST_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID == 1'b1))) begin
        m_axis_spikes_TID_int_regslice = grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TID;
    end else begin
        m_axis_spikes_TID_int_regslice = m_axis_spikes_TID_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID == 1'b1))) begin
        m_axis_spikes_TKEEP_int_regslice = grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TKEEP;
    end else begin
        m_axis_spikes_TKEEP_int_regslice = m_axis_spikes_TKEEP_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID == 1'b1))) begin
        m_axis_spikes_TLAST_int_regslice = grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TLAST;
    end else begin
        m_axis_spikes_TLAST_int_regslice = m_axis_spikes_TLAST_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID == 1'b1))) begin
        m_axis_spikes_TSTRB_int_regslice = grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TSTRB;
    end else begin
        m_axis_spikes_TSTRB_int_regslice = m_axis_spikes_TSTRB_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID == 1'b1))) begin
        m_axis_spikes_TUSER_int_regslice = grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TUSER;
    end else begin
        m_axis_spikes_TUSER_int_regslice = m_axis_spikes_TUSER_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        s_axis_spikes_TREADY_int_regslice = grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_s_axis_spikes_TREADY;
    end else begin
        s_axis_spikes_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        snn_enable = enable_fu_425_p1;
    end else begin
        snn_enable = snn_enable_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        snn_reset = ctrl_reg[32'd1];
    end else begin
        snn_reset = snn_reset_preg;
    end
end

always @ (*) begin
    if (((regslice_both_m_axis_spikes_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        spike_count_reg_ap_vld = 1'b1;
    end else begin
        spike_count_reg_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_m_axis_spikes_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        status_reg_ap_vld = 1'b1;
    end else begin
        status_reg_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        threshold_out = trunc_ln119_fu_551_p1;
    end else begin
        threshold_out = threshold_out_preg;
    end
end

always @ (*) begin
    if (((regslice_both_m_axis_spikes_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        version_reg_ap_vld = 1'b1;
    end else begin
        version_reg_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_m_axis_spikes_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        weight_sum_reg_ap_vld = 1'b1;
    end else begin
        weight_sum_reg_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((regslice_both_m_axis_spikes_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign clear_counters_fu_439_p3 = ctrl_reg[32'd2];

assign enable_fu_425_p1 = ctrl_reg[0:0];

assign grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start = grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start_reg;

assign grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TREADY = (m_axis_spikes_TREADY_int_regslice & ap_CS_fsm_state3);

assign icmp_ln122_fu_606_p2 = ((time_steps_1_reg_756 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_455_p2 = ((time_steps_reg == 32'd0) ? 1'b1 : 1'b0);

assign m_axis_spikes_TVALID = regslice_both_m_axis_spikes_V_data_V_U_vld_out;

assign m_axis_spikes_TVALID_int_regslice = grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID;

assign or_ln129_fu_575_p2 = (xor_ln129_fu_565_p2 | xor_ln129_1_fu_570_p2);

assign or_ln143_fu_587_p2 = (xor_ln143_fu_582_p2 | xor_ln129_fu_565_p2);

assign or_ln161_fu_599_p2 = (xor_ln161_fu_594_p2 | xor_ln129_fu_565_p2);

assign reset_fu_430_p3 = ctrl_reg[32'd1];

assign s_axis_spikes_TREADY = regslice_both_s_axis_spikes_V_data_V_U_ack_in;

assign spike_in_neuron_id = grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi4_out;

assign spike_in_valid = grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05623_phi_out;

assign spike_in_weight = grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi_out;

assign spike_out_ready = grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05525_phi_out;

assign status_fu_655_p5 = {{{{first_spike_pending}, {8'd0}}, {trunc_ln206_fu_637_p1}}, {zext_ln206_fu_647_p1}};

assign status_reg = status_fu_655_p5;

assign time_steps_1_fu_465_p3 = ((icmp_ln87_fu_455_p2[0:0] == 1'b1) ? 16'd1 : time_steps_fu_461_p1);

assign time_steps_fu_461_p1 = time_steps_reg[15:0];

assign tmp_9_fu_627_p3 = {{snn_busy_read_reg_677}, {snn_ready_read_reg_682}};

assign tmp_s_fu_640_p3 = {{first_spike_only_reg_749}, {zext_ln205_fu_633_p1}};

assign trunc_ln119_fu_551_p1 = config_reg[15:0];

assign trunc_ln206_fu_637_p1 = mode_reg_read_reg_708[1:0];

assign xor_ln129_1_fu_570_p2 = (spike_in_ready_read_reg_703 ^ 1'd1);

assign xor_ln129_fu_565_p2 = (enable_reg_737 ^ 1'd1);

assign xor_ln143_fu_582_p2 = (first_spike_only_reg_749 ^ 1'd1);

assign xor_ln161_fu_594_p2 = (spike_out_valid_read_reg_698 ^ 1'd1);

assign zext_ln205_fu_633_p1 = tmp_9_fu_627_p3;

assign zext_ln206_fu_647_p1 = tmp_s_fu_640_p3;

endmodule //snn_inference_profile_hls
