// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_inference_profile_hls_snn_inference_profile_hls_Pipeline_TIME_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axis_spikes_TREADY,
        s_axis_spikes_TVALID,
        time_steps_1,
        empty_21,
        or_ln161,
        or_ln143,
        or_ln129,
        s_axis_spikes_TDATA,
        s_axis_spikes_TREADY,
        s_axis_spikes_TKEEP,
        s_axis_spikes_TSTRB,
        s_axis_spikes_TUSER,
        s_axis_spikes_TLAST,
        s_axis_spikes_TID,
        s_axis_spikes_TDEST,
        m_axis_spikes_TDATA,
        m_axis_spikes_TVALID,
        m_axis_spikes_TKEEP,
        m_axis_spikes_TSTRB,
        m_axis_spikes_TUSER,
        m_axis_spikes_TLAST,
        m_axis_spikes_TID,
        m_axis_spikes_TDEST,
        empty,
        spike_out_weight,
        zext_ln162,
        spike_out_neuron_id,
        p_0_0_05525_phi_out,
        p_0_0_05525_phi_out_ap_vld,
        p_phi_out,
        p_phi_out_ap_vld,
        p_phi4_out,
        p_phi4_out_ap_vld,
        p_0_0_05623_phi_out,
        p_0_0_05623_phi_out_ap_vld,
        spike_out_ack_toggle_i,
        spike_out_ack_toggle_o,
        spike_out_ack_toggle_o_ap_vld,
        spike_in_valid_toggle_i,
        spike_in_valid_toggle_o,
        spike_in_valid_toggle_o_ap_vld,
        spike_counter_i,
        spike_counter_o,
        spike_counter_o_ap_vld,
        first_spike_pending_i,
        first_spike_pending_o,
        first_spike_pending_o_ap_vld,
        first_spike_pending_id_i,
        first_spike_pending_id_o,
        first_spike_pending_id_o_ap_vld,
        first_spike_pending_weight_i,
        first_spike_pending_weight_o,
        first_spike_pending_weight_o_ap_vld,
        timestamp_i,
        timestamp_o,
        timestamp_o_ap_vld,
        first_spike_sent_i,
        first_spike_sent_o,
        first_spike_sent_o_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   m_axis_spikes_TREADY;
input   s_axis_spikes_TVALID;
input  [15:0] time_steps_1;
input  [0:0] empty_21;
input  [0:0] or_ln161;
input  [0:0] or_ln143;
input  [0:0] or_ln129;
input  [31:0] s_axis_spikes_TDATA;
output   s_axis_spikes_TREADY;
input  [3:0] s_axis_spikes_TKEEP;
input  [3:0] s_axis_spikes_TSTRB;
input  [0:0] s_axis_spikes_TUSER;
input  [0:0] s_axis_spikes_TLAST;
input  [0:0] s_axis_spikes_TID;
input  [0:0] s_axis_spikes_TDEST;
output  [31:0] m_axis_spikes_TDATA;
output   m_axis_spikes_TVALID;
output  [3:0] m_axis_spikes_TKEEP;
output  [3:0] m_axis_spikes_TSTRB;
output  [0:0] m_axis_spikes_TUSER;
output  [0:0] m_axis_spikes_TLAST;
output  [0:0] m_axis_spikes_TID;
output  [0:0] m_axis_spikes_TDEST;
input  [0:0] empty;
input  [7:0] spike_out_weight;
input  [10:0] zext_ln162;
input  [10:0] spike_out_neuron_id;
output  [0:0] p_0_0_05525_phi_out;
output   p_0_0_05525_phi_out_ap_vld;
output  [7:0] p_phi_out;
output   p_phi_out_ap_vld;
output  [10:0] p_phi4_out;
output   p_phi4_out_ap_vld;
output  [0:0] p_0_0_05623_phi_out;
output   p_0_0_05623_phi_out_ap_vld;
input  [0:0] spike_out_ack_toggle_i;
output  [0:0] spike_out_ack_toggle_o;
output   spike_out_ack_toggle_o_ap_vld;
input  [0:0] spike_in_valid_toggle_i;
output  [0:0] spike_in_valid_toggle_o;
output   spike_in_valid_toggle_o_ap_vld;
input  [31:0] spike_counter_i;
output  [31:0] spike_counter_o;
output   spike_counter_o_ap_vld;
input  [0:0] first_spike_pending_i;
output  [0:0] first_spike_pending_o;
output   first_spike_pending_o_ap_vld;
input  [10:0] first_spike_pending_id_i;
output  [10:0] first_spike_pending_id_o;
output   first_spike_pending_id_o_ap_vld;
input  [7:0] first_spike_pending_weight_i;
output  [7:0] first_spike_pending_weight_o;
output   first_spike_pending_weight_o_ap_vld;
input  [31:0] timestamp_i;
output  [31:0] timestamp_o;
output   timestamp_o_ap_vld;
input  [0:0] first_spike_sent_i;
output  [0:0] first_spike_sent_o;
output   first_spike_sent_o_ap_vld;

reg ap_idle;
reg s_axis_spikes_TREADY;
reg[31:0] m_axis_spikes_TDATA;
reg m_axis_spikes_TVALID;
reg p_0_0_05525_phi_out_ap_vld;
reg p_phi_out_ap_vld;
reg p_phi4_out_ap_vld;
reg p_0_0_05623_phi_out_ap_vld;
reg[0:0] spike_out_ack_toggle_o;
reg spike_out_ack_toggle_o_ap_vld;
reg[0:0] spike_in_valid_toggle_o;
reg spike_in_valid_toggle_o_ap_vld;
reg[31:0] spike_counter_o;
reg spike_counter_o_ap_vld;
reg[0:0] first_spike_pending_o;
reg first_spike_pending_o_ap_vld;
reg[10:0] first_spike_pending_id_o;
reg first_spike_pending_id_o_ap_vld;
reg[7:0] first_spike_pending_weight_o;
reg first_spike_pending_weight_o_ap_vld;
reg[31:0] timestamp_o;
reg timestamp_o_ap_vld;
reg[0:0] first_spike_sent_o;
reg first_spike_sent_o_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] or_ln161_read_reg_674;
wire   [0:0] tmp_reg_662;
wire   [0:0] grp_nbwritereq_fu_258_p9;
reg    ap_predicate_op82_write_state3;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln122_fu_407_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln122_reg_687;
wire   [0:0] or_ln129_read_reg_666;
reg   [0:0] tmp_2_reg_691;
reg    ap_predicate_op48_read_state2;
reg    ap_block_state2_pp0_stage1_iter0_grp1;
reg    ap_block_pp0_stage1_subdone_grp1_done_reg;
reg    ap_block_pp0_stage1_subdone_grp1;
reg    ap_block_pp0_stage1_subdone;
wire   [0:0] grp_load_fu_387_p1;
reg    ap_predicate_op68_write_state2;
reg    ap_block_state2_pp0_stage1_iter0_grp2;
reg    ap_block_pp0_stage1_subdone_grp2_done_reg;
reg    ap_block_pp0_stage1_subdone_grp2;
reg    ap_enable_reg_pp0_iter0_reg;
reg    s_axis_spikes_TDATA_blk_n;
wire    ap_block_pp0_stage1_grp1;
reg    m_axis_spikes_TDATA_blk_n;
wire    ap_block_pp0_stage1_grp2;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] or_ln129_read_read_fu_190_p2;
wire   [0:0] tmp_1_reg_678;
wire   [12:0] zext_ln162_cast_fu_395_p1;
reg   [12:0] zext_ln162_cast_reg_682;
wire   [0:0] tmp_2_nbreadreq_fu_220_p9;
reg   [0:0] first_spike_sent_load_reg_701;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
reg   [7:0] ap_phi_mux_empty_27_phi_fu_341_p6;
reg    ap_block_pp0_stage1_11001_grp1;
reg   [10:0] ap_phi_mux_empty_28_phi_fu_355_p6;
wire   [10:0] trunc_ln136_fu_472_p1;
reg   [0:0] ap_phi_mux_p_0_0_05623_phi_fu_368_p6;
wire   [0:0] xor_ln134_fu_459_p2;
wire   [0:0] ap_phi_reg_pp0_iter0_p_0_0_05623_reg_365;
reg   [0:0] ap_phi_mux_p_0_0_05525_phi_fu_379_p6;
wire   [0:0] xor_ln192_fu_570_p2;
wire   [0:0] ap_phi_reg_pp0_iter1_p_0_0_05525_reg_376;
wire    ap_block_pp0_stage1_grp0;
wire   [31:0] add_ln138_fu_423_p2;
wire    ap_block_pp0_stage0_grp0;
reg    ap_block_pp0_stage1_11001_grp2;
wire   [31:0] add_ln198_fu_592_p2;
reg   [0:0] p_0_0_05623_phi_fu_146;
reg   [0:0] p_0_0_05525_phi_fu_150;
reg   [10:0] p_phi4_fu_154;
reg   [7:0] p_phi_fu_158;
reg   [15:0] t_fu_162;
wire   [15:0] t_2_fu_413_p2;
wire    ap_loop_init;
reg   [15:0] ap_sig_allocacmp_t_1;
wire   [31:0] tmp_4_fu_498_p4;
reg    ap_block_pp0_stage1_01001_grp2;
wire   [31:0] tmp_8_fu_539_p4;
reg    ap_block_pp0_stage0_01001;
wire    ap_block_pp0_stage0_01001_grp0;
wire   [10:0] trunc_ln149_fu_494_p1;
wire   [12:0] zext_ln148_fu_486_p1;
wire   [10:0] trunc_ln179_fu_535_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp2_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 p_0_0_05623_phi_fu_146 = 1'd0;
#0 p_0_0_05525_phi_fu_150 = 1'd0;
#0 p_phi4_fu_154 = 11'd0;
#0 p_phi_fu_158 = 8'd0;
#0 t_fu_162 = 16'd0;
#0 ap_done_reg = 1'b0;
end

snn_inference_profile_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp1)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp2)) begin
                ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln122_fu_407_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            t_fu_162 <= t_2_fu_413_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_162 <= 16'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        first_spike_sent_load_reg_701 <= first_spike_sent_i;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln122_reg_687 <= icmp_ln122_fu_407_p2;
        tmp_2_reg_691 <= tmp_2_nbreadreq_fu_220_p9;
        zext_ln162_cast_reg_682[10 : 0] <= zext_ln162_cast_fu_395_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_05525_phi_fu_150 <= ap_phi_mux_p_0_0_05525_phi_fu_379_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln122_reg_687 == 1'd0) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        p_0_0_05623_phi_fu_146 <= ap_phi_mux_p_0_0_05623_phi_fu_368_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln122_reg_687 == 1'd0) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        p_phi4_fu_154 <= ap_phi_mux_empty_28_phi_fu_355_p6;
        p_phi_fu_158 <= ap_phi_mux_empty_27_phi_fu_341_p6;
    end
end

always @ (*) begin
    if (((icmp_ln122_fu_407_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_691 == 1'd1) & (or_ln129 == 1'd0) & (icmp_ln122_reg_687 == 1'd0))) begin
        ap_phi_mux_empty_27_phi_fu_341_p6 = {{s_axis_spikes_TDATA[20:13]}};
    end else begin
        ap_phi_mux_empty_27_phi_fu_341_p6 = 8'd0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_691 == 1'd1) & (or_ln129 == 1'd0) & (icmp_ln122_reg_687 == 1'd0))) begin
        ap_phi_mux_empty_28_phi_fu_355_p6 = trunc_ln136_fu_472_p1;
    end else begin
        ap_phi_mux_empty_28_phi_fu_355_p6 = 11'd0;
    end
end

always @ (*) begin
    if ((((icmp_ln122_reg_687 == 1'd0) & (grp_nbwritereq_fu_258_p9 == 1'd0) & (empty == 1'd0) & (or_ln161 == 1'd0)) | ((icmp_ln122_reg_687 == 1'd0) & (or_ln161_read_reg_674 == 1'd1)))) begin
        ap_phi_mux_p_0_0_05525_phi_fu_379_p6 = spike_out_ack_toggle_i;
    end else if ((((icmp_ln122_reg_687 == 1'd0) & (grp_nbwritereq_fu_258_p9 == 1'd1) & (or_ln161 == 1'd0)) | ((icmp_ln122_reg_687 == 1'd0) & (tmp_reg_662 == 1'd1) & (or_ln161 == 1'd0)))) begin
        ap_phi_mux_p_0_0_05525_phi_fu_379_p6 = xor_ln192_fu_570_p2;
    end else begin
        ap_phi_mux_p_0_0_05525_phi_fu_379_p6 = ap_phi_reg_pp0_iter1_p_0_0_05525_reg_376;
    end
end

always @ (*) begin
    if ((((tmp_2_reg_691 == 1'd0) & (or_ln129 == 1'd0) & (icmp_ln122_reg_687 == 1'd0)) | ((or_ln129_read_reg_666 == 1'd1) & (icmp_ln122_reg_687 == 1'd0)))) begin
        ap_phi_mux_p_0_0_05623_phi_fu_368_p6 = spike_in_valid_toggle_i;
    end else if (((tmp_2_reg_691 == 1'd1) & (or_ln129 == 1'd0) & (icmp_ln122_reg_687 == 1'd0))) begin
        ap_phi_mux_p_0_0_05623_phi_fu_368_p6 = xor_ln134_fu_459_p2;
    end else begin
        ap_phi_mux_p_0_0_05623_phi_fu_368_p6 = ap_phi_reg_pp0_iter0_p_0_0_05623_reg_365;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_t_1 = 16'd0;
    end else begin
        ap_sig_allocacmp_t_1 = t_fu_162;
    end
end

always @ (*) begin
    if (((grp_load_fu_387_p1 == 1'd0) & (1'b0 == ap_block_pp0_stage0_grp0) & (tmp_reg_662 == 1'd1) & (or_ln161 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (first_spike_sent_load_reg_701 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        first_spike_pending_id_o = spike_out_neuron_id;
    end else begin
        first_spike_pending_id_o = first_spike_pending_id_i;
    end
end

always @ (*) begin
    if (((grp_load_fu_387_p1 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (tmp_reg_662 == 1'd1) & (or_ln161 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (first_spike_sent_load_reg_701 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        first_spike_pending_id_o_ap_vld = 1'b1;
    end else begin
        first_spike_pending_id_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((first_spike_pending_i == 1'd1) & (or_ln143 == 1'd0) & (icmp_ln122_reg_687 == 1'd0) & (1'b0 == ap_block_pp0_stage1_grp2) & (grp_nbwritereq_fu_258_p9 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        first_spike_pending_o = 1'd0;
    end else if (((grp_load_fu_387_p1 == 1'd0) & (1'b0 == ap_block_pp0_stage0_grp0) & (tmp_reg_662 == 1'd1) & (or_ln161 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (first_spike_sent_load_reg_701 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        first_spike_pending_o = 1'd1;
    end else begin
        first_spike_pending_o = first_spike_pending_i;
    end
end

always @ (*) begin
    if ((((first_spike_pending_i == 1'd1) & (or_ln143 == 1'd0) & (icmp_ln122_reg_687 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (grp_nbwritereq_fu_258_p9 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((grp_load_fu_387_p1 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (tmp_reg_662 == 1'd1) & (or_ln161 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (first_spike_sent_load_reg_701 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        first_spike_pending_o_ap_vld = 1'b1;
    end else begin
        first_spike_pending_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_load_fu_387_p1 == 1'd0) & (1'b0 == ap_block_pp0_stage0_grp0) & (tmp_reg_662 == 1'd1) & (or_ln161 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (first_spike_sent_load_reg_701 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        first_spike_pending_weight_o = spike_out_weight;
    end else begin
        first_spike_pending_weight_o = first_spike_pending_weight_i;
    end
end

always @ (*) begin
    if (((grp_load_fu_387_p1 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (tmp_reg_662 == 1'd1) & (or_ln161 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (first_spike_sent_load_reg_701 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        first_spike_pending_weight_o_ap_vld = 1'b1;
    end else begin
        first_spike_pending_weight_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_load_fu_387_p1 == 1'd0) & (1'b0 == ap_block_pp0_stage0_grp0) & (tmp_reg_662 == 1'd1) & (or_ln161 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (first_spike_sent_load_reg_701 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        first_spike_sent_o = 1'd1;
    end else begin
        first_spike_sent_o = first_spike_sent_i;
    end
end

always @ (*) begin
    if (((grp_load_fu_387_p1 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (tmp_reg_662 == 1'd1) & (or_ln161 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (first_spike_sent_load_reg_701 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        first_spike_sent_o_ap_vld = 1'b1;
    end else begin
        first_spike_sent_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_predicate_op82_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axis_spikes_TDATA = tmp_8_fu_539_p4;
    end else if (((1'b0 == ap_block_pp0_stage1_01001_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (ap_predicate_op68_write_state2 == 1'b1))) begin
        m_axis_spikes_TDATA = tmp_4_fu_498_p4;
    end else begin
        m_axis_spikes_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op82_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (ap_predicate_op68_write_state2 == 1'b1)))) begin
        m_axis_spikes_TDATA_blk_n = m_axis_spikes_TREADY;
    end else begin
        m_axis_spikes_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (ap_predicate_op68_write_state2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op82_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        m_axis_spikes_TVALID = 1'b1;
    end else begin
        m_axis_spikes_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln122_fu_407_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_05525_phi_out_ap_vld = 1'b1;
    end else begin
        p_0_0_05525_phi_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln122_fu_407_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_05623_phi_out_ap_vld = 1'b1;
    end else begin
        p_0_0_05623_phi_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln122_fu_407_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_phi4_out_ap_vld = 1'b1;
    end else begin
        p_phi4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln122_fu_407_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_phi_out_ap_vld = 1'b1;
    end else begin
        p_phi_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op48_read_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        s_axis_spikes_TDATA_blk_n = s_axis_spikes_TVALID;
    end else begin
        s_axis_spikes_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op48_read_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        s_axis_spikes_TREADY = 1'b1;
    end else begin
        s_axis_spikes_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln122_fu_407_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (tmp_2_nbreadreq_fu_220_p9 == 1'd1) & (or_ln129_read_read_fu_190_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        spike_counter_o = add_ln138_fu_423_p2;
    end else begin
        spike_counter_o = spike_counter_i;
    end
end

always @ (*) begin
    if (((icmp_ln122_fu_407_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_nbreadreq_fu_220_p9 == 1'd1) & (or_ln129_read_read_fu_190_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        spike_counter_o_ap_vld = 1'b1;
    end else begin
        spike_counter_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_691 == 1'd1) & (or_ln129 == 1'd0) & (icmp_ln122_reg_687 == 1'd0) & (1'b0 == ap_block_pp0_stage1_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        spike_in_valid_toggle_o = xor_ln134_fu_459_p2;
    end else begin
        spike_in_valid_toggle_o = spike_in_valid_toggle_i;
    end
end

always @ (*) begin
    if (((tmp_2_reg_691 == 1'd1) & (or_ln129 == 1'd0) & (icmp_ln122_reg_687 == 1'd0) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        spike_in_valid_toggle_o_ap_vld = 1'b1;
    end else begin
        spike_in_valid_toggle_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((icmp_ln122_reg_687 == 1'd0) & (grp_nbwritereq_fu_258_p9 == 1'd1) & (or_ln161 == 1'd0)) | ((icmp_ln122_reg_687 == 1'd0) & (tmp_reg_662 == 1'd1) & (or_ln161 == 1'd0))))) begin
        spike_out_ack_toggle_o = xor_ln192_fu_570_p2;
    end else begin
        spike_out_ack_toggle_o = spike_out_ack_toggle_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((icmp_ln122_reg_687 == 1'd0) & (grp_nbwritereq_fu_258_p9 == 1'd1) & (or_ln161 == 1'd0)) | ((icmp_ln122_reg_687 == 1'd0) & (tmp_reg_662 == 1'd1) & (or_ln161 == 1'd0))))) begin
        spike_out_ack_toggle_o_ap_vld = 1'b1;
    end else begin
        spike_out_ack_toggle_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_1_reg_678 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        timestamp_o = add_ln198_fu_592_p2;
    end else begin
        timestamp_o = timestamp_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_1_reg_678 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        timestamp_o_ap_vld = 1'b1;
    end else begin
        timestamp_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln138_fu_423_p2 = (spike_counter_i + 32'd1);

assign add_ln198_fu_592_p2 = (timestamp_i + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1));
end

assign ap_block_pp0_stage0_01001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001_grp2 = ((1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp2 = ((1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (((1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1)) | ((1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp2))));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp1 = ((1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp2 = ((1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_grp1 = ((ap_predicate_op48_read_state2 == 1'b1) & (s_axis_spikes_TVALID == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_grp2 = ((m_axis_spikes_TREADY == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((ap_predicate_op82_write_state3 == 1'b1) & (m_axis_spikes_TREADY == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_p_0_0_05623_reg_365 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_05525_reg_376 = 'bx;

always @ (*) begin
    ap_predicate_op48_read_state2 = ((tmp_2_reg_691 == 1'd1) & (or_ln129 == 1'd0) & (icmp_ln122_reg_687 == 1'd0));
end

always @ (*) begin
    ap_predicate_op68_write_state2 = ((first_spike_pending_i == 1'd1) & (or_ln143 == 1'd0) & (icmp_ln122_reg_687 == 1'd0) & (grp_nbwritereq_fu_258_p9 == 1'd1));
end

always @ (*) begin
    ap_predicate_op82_write_state3 = ((grp_nbwritereq_fu_258_p9 == 1'd1) & (empty == 1'd0) & (or_ln161 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign grp_load_fu_387_p1 = first_spike_pending_i;

assign grp_nbwritereq_fu_258_p9 = m_axis_spikes_TREADY;

assign icmp_ln122_fu_407_p2 = ((ap_sig_allocacmp_t_1 == time_steps_1) ? 1'b1 : 1'b0);

assign m_axis_spikes_TDEST = 1'd0;

assign m_axis_spikes_TID = 1'd0;

assign m_axis_spikes_TKEEP = 4'd15;

assign m_axis_spikes_TLAST = 1'd1;

assign m_axis_spikes_TSTRB = 4'd15;

assign m_axis_spikes_TUSER = 1'd0;

assign or_ln129_read_read_fu_190_p2 = or_ln129;

assign or_ln129_read_reg_666 = or_ln129;

assign or_ln161_read_reg_674 = or_ln161;

assign p_0_0_05525_phi_out = p_0_0_05525_phi_fu_150;

assign p_0_0_05623_phi_out = p_0_0_05623_phi_fu_146;

assign p_phi4_out = p_phi4_fu_154;

assign p_phi_out = p_phi_fu_158;

assign t_2_fu_413_p2 = (ap_sig_allocacmp_t_1 + 16'd1);

assign tmp_1_reg_678 = empty_21;

assign tmp_2_nbreadreq_fu_220_p9 = s_axis_spikes_TVALID;

assign tmp_4_fu_498_p4 = {{{trunc_ln149_fu_494_p1}, {first_spike_pending_weight_i}}, {zext_ln148_fu_486_p1}};

assign tmp_8_fu_539_p4 = {{{trunc_ln179_fu_535_p1}, {spike_out_weight}}, {zext_ln162_cast_reg_682}};

assign tmp_reg_662 = empty;

assign trunc_ln136_fu_472_p1 = s_axis_spikes_TDATA[10:0];

assign trunc_ln149_fu_494_p1 = timestamp_i[10:0];

assign trunc_ln179_fu_535_p1 = timestamp_i[10:0];

assign xor_ln134_fu_459_p2 = (spike_in_valid_toggle_i ^ 1'd1);

assign xor_ln192_fu_570_p2 = (spike_out_ack_toggle_i ^ 1'd1);

assign zext_ln148_fu_486_p1 = first_spike_pending_id_i;

assign zext_ln162_cast_fu_395_p1 = zext_ln162;

always @ (posedge ap_clk) begin
    zext_ln162_cast_reg_682[12:11] <= 2'b00;
end

endmodule //snn_inference_profile_hls_snn_inference_profile_hls_Pipeline_TIME_LOOP
