[hls]
relative_roots=/home/ym/xilinx_project/Event-Driven-Spiking-Neural-Network-Accelerator-for-FPGA/hardware/hls
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=snn_inference_profile_hls/TIME_LOOP 


