-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity snn_inference_profile_hls_snn_inference_profile_hls_Pipeline_TIME_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axis_spikes_TREADY : IN STD_LOGIC;
    s_axis_spikes_TVALID : IN STD_LOGIC;
    time_steps_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    empty_21 : IN STD_LOGIC_VECTOR (0 downto 0);
    or_ln161 : IN STD_LOGIC_VECTOR (0 downto 0);
    or_ln143 : IN STD_LOGIC_VECTOR (0 downto 0);
    or_ln129 : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_spikes_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    s_axis_spikes_TREADY : OUT STD_LOGIC;
    s_axis_spikes_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    s_axis_spikes_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    s_axis_spikes_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_spikes_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_spikes_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_spikes_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axis_spikes_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axis_spikes_TVALID : OUT STD_LOGIC;
    m_axis_spikes_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_spikes_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_spikes_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_spikes_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_spikes_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_spikes_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    empty : IN STD_LOGIC_VECTOR (0 downto 0);
    spike_out_weight : IN STD_LOGIC_VECTOR (7 downto 0);
    zext_ln162 : IN STD_LOGIC_VECTOR (10 downto 0);
    spike_out_neuron_id : IN STD_LOGIC_VECTOR (10 downto 0);
    p_0_0_05525_phi_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_0_0_05525_phi_out_ap_vld : OUT STD_LOGIC;
    p_phi_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_phi_out_ap_vld : OUT STD_LOGIC;
    p_phi4_out : OUT STD_LOGIC_VECTOR (10 downto 0);
    p_phi4_out_ap_vld : OUT STD_LOGIC;
    p_0_0_05623_phi_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_0_0_05623_phi_out_ap_vld : OUT STD_LOGIC;
    spike_out_ack_toggle_i : IN STD_LOGIC_VECTOR (0 downto 0);
    spike_out_ack_toggle_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    spike_out_ack_toggle_o_ap_vld : OUT STD_LOGIC;
    spike_in_valid_toggle_i : IN STD_LOGIC_VECTOR (0 downto 0);
    spike_in_valid_toggle_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    spike_in_valid_toggle_o_ap_vld : OUT STD_LOGIC;
    spike_counter_i : IN STD_LOGIC_VECTOR (31 downto 0);
    spike_counter_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    spike_counter_o_ap_vld : OUT STD_LOGIC;
    first_spike_pending_i : IN STD_LOGIC_VECTOR (0 downto 0);
    first_spike_pending_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    first_spike_pending_o_ap_vld : OUT STD_LOGIC;
    first_spike_pending_id_i : IN STD_LOGIC_VECTOR (10 downto 0);
    first_spike_pending_id_o : OUT STD_LOGIC_VECTOR (10 downto 0);
    first_spike_pending_id_o_ap_vld : OUT STD_LOGIC;
    first_spike_pending_weight_i : IN STD_LOGIC_VECTOR (7 downto 0);
    first_spike_pending_weight_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    first_spike_pending_weight_o_ap_vld : OUT STD_LOGIC;
    timestamp_i : IN STD_LOGIC_VECTOR (31 downto 0);
    timestamp_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    timestamp_o_ap_vld : OUT STD_LOGIC;
    first_spike_sent_i : IN STD_LOGIC_VECTOR (0 downto 0);
    first_spike_sent_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    first_spike_sent_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of snn_inference_profile_hls_snn_inference_profile_hls_Pipeline_TIME_LOOP is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal or_ln161_read_reg_674 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_662 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_nbwritereq_fu_258_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op82_write_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln122_fu_407_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal icmp_ln122_reg_687 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln129_read_reg_666 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_691 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op48_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage1_iter0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal grp_load_fu_387_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op68_write_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage1_iter0_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp2 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal s_axis_spikes_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage1_grp1 : BOOLEAN;
    signal m_axis_spikes_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage1_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal or_ln129_read_read_fu_190_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_678 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln162_cast_fu_395_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln162_cast_reg_682 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_2_nbreadreq_fu_220_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_spike_sent_load_reg_701 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp0 : BOOLEAN;
    signal ap_phi_mux_empty_27_phi_fu_341_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage1_11001_grp1 : BOOLEAN;
    signal ap_phi_mux_empty_28_phi_fu_355_p6 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln136_fu_472_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_phi_mux_p_0_0_05623_phi_fu_368_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln134_fu_459_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_0_05623_reg_365 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_p_0_0_05525_phi_fu_379_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln192_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_p_0_0_05525_reg_376 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1_grp0 : BOOLEAN;
    signal add_ln138_fu_423_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp2 : BOOLEAN;
    signal add_ln198_fu_592_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_05623_phi_fu_146 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal p_0_0_05525_phi_fu_150 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal p_phi4_fu_154 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal p_phi_fu_158 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal t_fu_162 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal t_2_fu_413_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_t_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_498_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_01001_grp2 : BOOLEAN;
    signal tmp_8_fu_539_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp0 : BOOLEAN;
    signal trunc_ln149_fu_494_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln148_fu_486_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln179_fu_535_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component snn_inference_profile_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component snn_inference_profile_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp1_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1)) then 
                        ap_block_pp0_stage1_subdone_grp1_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2)) then 
                        ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    t_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln122_fu_407_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    t_fu_162 <= t_2_fu_413_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    t_fu_162 <= ap_const_lv16_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                first_spike_sent_load_reg_701 <= first_spike_sent_i;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln122_reg_687 <= icmp_ln122_fu_407_p2;
                tmp_2_reg_691 <= tmp_2_nbreadreq_fu_220_p9;
                    zext_ln162_cast_reg_682(10 downto 0) <= zext_ln162_cast_fu_395_p1(10 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                p_0_0_05525_phi_fu_150 <= ap_phi_mux_p_0_0_05525_phi_fu_379_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln122_reg_687 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then
                p_0_0_05623_phi_fu_146 <= ap_phi_mux_p_0_0_05623_phi_fu_368_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln122_reg_687 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then
                p_phi4_fu_154 <= ap_phi_mux_empty_28_phi_fu_355_p6;
                p_phi_fu_158 <= ap_phi_mux_empty_27_phi_fu_341_p6;
            end if;
        end if;
    end process;
    zext_ln162_cast_reg_682(12 downto 11) <= "00";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0, ap_block_pp0_stage1_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln138_fu_423_p2 <= std_logic_vector(unsigned(spike_counter_i) + unsigned(ap_const_lv32_1));
    add_ln198_fu_592_p2 <= std_logic_vector(unsigned(timestamp_i) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state3_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter1));
    end process;

        ap_block_pp0_stage0_01001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state3_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state3_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_grp2_assign_proc : process(ap_block_state2_pp0_stage1_iter0_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage1_01001_grp2 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_grp1_assign_proc : process(ap_block_state2_pp0_stage1_iter0_grp1, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage1_11001_grp1 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_11001_grp2_assign_proc : process(ap_block_state2_pp0_stage1_iter0_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage1_11001_grp2 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_block_state2_pp0_stage1_iter0_grp1, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_block_state2_pp0_stage1_iter0_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp2))));
    end process;

        ap_block_pp0_stage1_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_grp1_assign_proc : process(ap_block_state2_pp0_stage1_iter0_grp1, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage1_subdone_grp1 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_subdone_grp2_assign_proc : process(ap_block_state2_pp0_stage1_iter0_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage1_subdone_grp2 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_state2_pp0_stage1_iter0_grp1_assign_proc : process(s_axis_spikes_TVALID, ap_predicate_op48_read_state2)
    begin
                ap_block_state2_pp0_stage1_iter0_grp1 <= ((ap_predicate_op48_read_state2 = ap_const_boolean_1) and (s_axis_spikes_TVALID = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage1_iter0_grp2_assign_proc : process(m_axis_spikes_TREADY, ap_predicate_op68_write_state2)
    begin
                ap_block_state2_pp0_stage1_iter0_grp2 <= ((m_axis_spikes_TREADY = ap_const_logic_0) and (ap_predicate_op68_write_state2 = ap_const_boolean_1));
    end process;


    ap_block_state3_pp0_stage0_iter1_assign_proc : process(m_axis_spikes_TREADY, ap_predicate_op82_write_state3)
    begin
                ap_block_state3_pp0_stage0_iter1 <= ((ap_predicate_op82_write_state3 = ap_const_boolean_1) and (m_axis_spikes_TREADY = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln122_fu_407_p2)
    begin
        if (((icmp_ln122_fu_407_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_empty_27_phi_fu_341_p6_assign_proc : process(icmp_ln122_reg_687, tmp_2_reg_691, or_ln129, s_axis_spikes_TDATA)
    begin
        if (((tmp_2_reg_691 = ap_const_lv1_1) and (or_ln129 = ap_const_lv1_0) and (icmp_ln122_reg_687 = ap_const_lv1_0))) then 
            ap_phi_mux_empty_27_phi_fu_341_p6 <= s_axis_spikes_TDATA(20 downto 13);
        else 
            ap_phi_mux_empty_27_phi_fu_341_p6 <= ap_const_lv8_0;
        end if; 
    end process;


    ap_phi_mux_empty_28_phi_fu_355_p6_assign_proc : process(icmp_ln122_reg_687, tmp_2_reg_691, or_ln129, trunc_ln136_fu_472_p1)
    begin
        if (((tmp_2_reg_691 = ap_const_lv1_1) and (or_ln129 = ap_const_lv1_0) and (icmp_ln122_reg_687 = ap_const_lv1_0))) then 
            ap_phi_mux_empty_28_phi_fu_355_p6 <= trunc_ln136_fu_472_p1;
        else 
            ap_phi_mux_empty_28_phi_fu_355_p6 <= ap_const_lv11_0;
        end if; 
    end process;


    ap_phi_mux_p_0_0_05525_phi_fu_379_p6_assign_proc : process(or_ln161_read_reg_674, tmp_reg_662, grp_nbwritereq_fu_258_p9, icmp_ln122_reg_687, or_ln161, empty, spike_out_ack_toggle_i, xor_ln192_fu_570_p2, ap_phi_reg_pp0_iter1_p_0_0_05525_reg_376)
    begin
        if ((((icmp_ln122_reg_687 = ap_const_lv1_0) and (grp_nbwritereq_fu_258_p9 = ap_const_lv1_0) and (empty = ap_const_lv1_0) and (or_ln161 = ap_const_lv1_0)) or ((icmp_ln122_reg_687 = ap_const_lv1_0) and (or_ln161_read_reg_674 = ap_const_lv1_1)))) then 
            ap_phi_mux_p_0_0_05525_phi_fu_379_p6 <= spike_out_ack_toggle_i;
        elsif ((((icmp_ln122_reg_687 = ap_const_lv1_0) and (grp_nbwritereq_fu_258_p9 = ap_const_lv1_1) and (or_ln161 = ap_const_lv1_0)) or ((icmp_ln122_reg_687 = ap_const_lv1_0) and (tmp_reg_662 = ap_const_lv1_1) and (or_ln161 = ap_const_lv1_0)))) then 
            ap_phi_mux_p_0_0_05525_phi_fu_379_p6 <= xor_ln192_fu_570_p2;
        else 
            ap_phi_mux_p_0_0_05525_phi_fu_379_p6 <= ap_phi_reg_pp0_iter1_p_0_0_05525_reg_376;
        end if; 
    end process;


    ap_phi_mux_p_0_0_05623_phi_fu_368_p6_assign_proc : process(icmp_ln122_reg_687, or_ln129_read_reg_666, tmp_2_reg_691, or_ln129, spike_in_valid_toggle_i, xor_ln134_fu_459_p2, ap_phi_reg_pp0_iter0_p_0_0_05623_reg_365)
    begin
        if ((((tmp_2_reg_691 = ap_const_lv1_0) and (or_ln129 = ap_const_lv1_0) and (icmp_ln122_reg_687 = ap_const_lv1_0)) or ((or_ln129_read_reg_666 = ap_const_lv1_1) and (icmp_ln122_reg_687 = ap_const_lv1_0)))) then 
            ap_phi_mux_p_0_0_05623_phi_fu_368_p6 <= spike_in_valid_toggle_i;
        elsif (((tmp_2_reg_691 = ap_const_lv1_1) and (or_ln129 = ap_const_lv1_0) and (icmp_ln122_reg_687 = ap_const_lv1_0))) then 
            ap_phi_mux_p_0_0_05623_phi_fu_368_p6 <= xor_ln134_fu_459_p2;
        else 
            ap_phi_mux_p_0_0_05623_phi_fu_368_p6 <= ap_phi_reg_pp0_iter0_p_0_0_05623_reg_365;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_p_0_0_05623_reg_365 <= "X";
    ap_phi_reg_pp0_iter1_p_0_0_05525_reg_376 <= "X";

    ap_predicate_op48_read_state2_assign_proc : process(icmp_ln122_reg_687, tmp_2_reg_691, or_ln129)
    begin
                ap_predicate_op48_read_state2 <= ((tmp_2_reg_691 = ap_const_lv1_1) and (or_ln129 = ap_const_lv1_0) and (icmp_ln122_reg_687 = ap_const_lv1_0));
    end process;


    ap_predicate_op68_write_state2_assign_proc : process(grp_nbwritereq_fu_258_p9, icmp_ln122_reg_687, or_ln143, first_spike_pending_i)
    begin
                ap_predicate_op68_write_state2 <= ((first_spike_pending_i = ap_const_lv1_1) and (or_ln143 = ap_const_lv1_0) and (icmp_ln122_reg_687 = ap_const_lv1_0) and (grp_nbwritereq_fu_258_p9 = ap_const_lv1_1));
    end process;


    ap_predicate_op82_write_state3_assign_proc : process(grp_nbwritereq_fu_258_p9, or_ln161, empty)
    begin
                ap_predicate_op82_write_state3 <= ((grp_nbwritereq_fu_258_p9 = ap_const_lv1_1) and (empty = ap_const_lv1_0) and (or_ln161 = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_t_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, t_fu_162, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_t_1 <= ap_const_lv16_0;
        else 
            ap_sig_allocacmp_t_1 <= t_fu_162;
        end if; 
    end process;


    first_spike_pending_id_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_662, grp_load_fu_387_p1, or_ln161, spike_out_neuron_id, first_spike_pending_id_i, first_spike_sent_load_reg_701, ap_block_pp0_stage0_grp0)
    begin
        if (((grp_load_fu_387_p1 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp0) and (tmp_reg_662 = ap_const_lv1_1) and (or_ln161 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (first_spike_sent_load_reg_701 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            first_spike_pending_id_o <= spike_out_neuron_id;
        else 
            first_spike_pending_id_o <= first_spike_pending_id_i;
        end if; 
    end process;


    first_spike_pending_id_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_662, grp_load_fu_387_p1, or_ln161, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, first_spike_sent_load_reg_701)
    begin
        if (((grp_load_fu_387_p1 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (tmp_reg_662 = ap_const_lv1_1) and (or_ln161 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (first_spike_sent_load_reg_701 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            first_spike_pending_id_o_ap_vld <= ap_const_logic_1;
        else 
            first_spike_pending_id_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    first_spike_pending_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_662, grp_nbwritereq_fu_258_p9, ap_CS_fsm_pp0_stage1, icmp_ln122_reg_687, grp_load_fu_387_p1, ap_enable_reg_pp0_iter0_reg, or_ln161, or_ln143, first_spike_pending_i, ap_block_pp0_stage1_grp2, first_spike_sent_load_reg_701, ap_block_pp0_stage0_grp0)
    begin
        if (((first_spike_pending_i = ap_const_lv1_1) and (or_ln143 = ap_const_lv1_0) and (icmp_ln122_reg_687 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp2) and (grp_nbwritereq_fu_258_p9 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            first_spike_pending_o <= ap_const_lv1_0;
        elsif (((grp_load_fu_387_p1 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp0) and (tmp_reg_662 = ap_const_lv1_1) and (or_ln161 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (first_spike_sent_load_reg_701 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            first_spike_pending_o <= ap_const_lv1_1;
        else 
            first_spike_pending_o <= first_spike_pending_i;
        end if; 
    end process;


    first_spike_pending_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_662, grp_nbwritereq_fu_258_p9, ap_CS_fsm_pp0_stage1, icmp_ln122_reg_687, grp_load_fu_387_p1, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg, or_ln161, or_ln143, first_spike_pending_i, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, first_spike_sent_load_reg_701, ap_block_pp0_stage1_11001_grp2)
    begin
        if ((((first_spike_pending_i = ap_const_lv1_1) and (or_ln143 = ap_const_lv1_0) and (icmp_ln122_reg_687 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (grp_nbwritereq_fu_258_p9 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((grp_load_fu_387_p1 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (tmp_reg_662 = ap_const_lv1_1) and (or_ln161 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (first_spike_sent_load_reg_701 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            first_spike_pending_o_ap_vld <= ap_const_logic_1;
        else 
            first_spike_pending_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    first_spike_pending_weight_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_662, grp_load_fu_387_p1, or_ln161, spike_out_weight, first_spike_pending_weight_i, first_spike_sent_load_reg_701, ap_block_pp0_stage0_grp0)
    begin
        if (((grp_load_fu_387_p1 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp0) and (tmp_reg_662 = ap_const_lv1_1) and (or_ln161 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (first_spike_sent_load_reg_701 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            first_spike_pending_weight_o <= spike_out_weight;
        else 
            first_spike_pending_weight_o <= first_spike_pending_weight_i;
        end if; 
    end process;


    first_spike_pending_weight_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_662, grp_load_fu_387_p1, or_ln161, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, first_spike_sent_load_reg_701)
    begin
        if (((grp_load_fu_387_p1 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (tmp_reg_662 = ap_const_lv1_1) and (or_ln161 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (first_spike_sent_load_reg_701 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            first_spike_pending_weight_o_ap_vld <= ap_const_logic_1;
        else 
            first_spike_pending_weight_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    first_spike_sent_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_662, grp_load_fu_387_p1, or_ln161, first_spike_sent_i, first_spike_sent_load_reg_701, ap_block_pp0_stage0_grp0)
    begin
        if (((grp_load_fu_387_p1 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp0) and (tmp_reg_662 = ap_const_lv1_1) and (or_ln161 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (first_spike_sent_load_reg_701 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            first_spike_sent_o <= ap_const_lv1_1;
        else 
            first_spike_sent_o <= first_spike_sent_i;
        end if; 
    end process;


    first_spike_sent_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_662, grp_load_fu_387_p1, or_ln161, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, first_spike_sent_load_reg_701)
    begin
        if (((grp_load_fu_387_p1 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (tmp_reg_662 = ap_const_lv1_1) and (or_ln161 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (first_spike_sent_load_reg_701 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            first_spike_sent_o_ap_vld <= ap_const_logic_1;
        else 
            first_spike_sent_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    grp_load_fu_387_p1 <= first_spike_pending_i;
    grp_nbwritereq_fu_258_p9 <= (0=>m_axis_spikes_TREADY, others=>'-');
    icmp_ln122_fu_407_p2 <= "1" when (ap_sig_allocacmp_t_1 = time_steps_1) else "0";

    m_axis_spikes_TDATA_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op82_write_state3, ap_CS_fsm_pp0_stage1, ap_predicate_op68_write_state2, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg, tmp_4_fu_498_p4, ap_block_pp0_stage1_01001_grp2, tmp_8_fu_539_p4, ap_block_pp0_stage0_01001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_predicate_op82_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axis_spikes_TDATA <= tmp_8_fu_539_p4;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_01001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_predicate_op68_write_state2 = ap_const_boolean_1))) then 
            m_axis_spikes_TDATA <= tmp_4_fu_498_p4;
        else 
            m_axis_spikes_TDATA <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axis_spikes_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axis_spikes_TREADY, ap_predicate_op82_write_state3, ap_CS_fsm_pp0_stage1, ap_predicate_op68_write_state2, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_grp2, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op82_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_predicate_op68_write_state2 = ap_const_boolean_1)))) then 
            m_axis_spikes_TDATA_blk_n <= m_axis_spikes_TREADY;
        else 
            m_axis_spikes_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    m_axis_spikes_TDEST <= ap_const_lv1_0;
    m_axis_spikes_TID <= ap_const_lv1_0;
    m_axis_spikes_TKEEP <= ap_const_lv4_F;
    m_axis_spikes_TLAST <= ap_const_lv1_1;
    m_axis_spikes_TSTRB <= ap_const_lv4_F;
    m_axis_spikes_TUSER <= ap_const_lv1_0;

    m_axis_spikes_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op82_write_state3, ap_CS_fsm_pp0_stage1, ap_predicate_op68_write_state2, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001_grp2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_predicate_op68_write_state2 = ap_const_boolean_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op82_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            m_axis_spikes_TVALID <= ap_const_logic_1;
        else 
            m_axis_spikes_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    or_ln129_read_read_fu_190_p2 <= or_ln129;
    or_ln129_read_reg_666 <= or_ln129;
    or_ln161_read_reg_674 <= or_ln161;
    p_0_0_05525_phi_out <= p_0_0_05525_phi_fu_150;

    p_0_0_05525_phi_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln122_fu_407_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln122_fu_407_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_0_05525_phi_out_ap_vld <= ap_const_logic_1;
        else 
            p_0_0_05525_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_0_0_05623_phi_out <= p_0_0_05623_phi_fu_146;

    p_0_0_05623_phi_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln122_fu_407_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln122_fu_407_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_0_05623_phi_out_ap_vld <= ap_const_logic_1;
        else 
            p_0_0_05623_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_phi4_out <= p_phi4_fu_154;

    p_phi4_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln122_fu_407_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln122_fu_407_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_phi4_out_ap_vld <= ap_const_logic_1;
        else 
            p_phi4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_phi_out <= p_phi_fu_158;

    p_phi_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln122_fu_407_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln122_fu_407_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_phi_out_ap_vld <= ap_const_logic_1;
        else 
            p_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    s_axis_spikes_TDATA_blk_n_assign_proc : process(s_axis_spikes_TVALID, ap_CS_fsm_pp0_stage1, ap_predicate_op48_read_state2, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_grp1)
    begin
        if (((ap_predicate_op48_read_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            s_axis_spikes_TDATA_blk_n <= s_axis_spikes_TVALID;
        else 
            s_axis_spikes_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_axis_spikes_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_predicate_op48_read_state2, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_11001_grp1)
    begin
        if (((ap_predicate_op48_read_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            s_axis_spikes_TREADY <= ap_const_logic_1;
        else 
            s_axis_spikes_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    spike_counter_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln122_fu_407_p2, spike_counter_i, ap_block_pp0_stage0, or_ln129_read_read_fu_190_p2, tmp_2_nbreadreq_fu_220_p9, add_ln138_fu_423_p2)
    begin
        if (((icmp_ln122_fu_407_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (tmp_2_nbreadreq_fu_220_p9 = ap_const_lv1_1) and (or_ln129_read_read_fu_190_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spike_counter_o <= add_ln138_fu_423_p2;
        else 
            spike_counter_o <= spike_counter_i;
        end if; 
    end process;


    spike_counter_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln122_fu_407_p2, ap_block_pp0_stage0_11001, or_ln129_read_read_fu_190_p2, tmp_2_nbreadreq_fu_220_p9)
    begin
        if (((icmp_ln122_fu_407_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_2_nbreadreq_fu_220_p9 = ap_const_lv1_1) and (or_ln129_read_read_fu_190_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spike_counter_o_ap_vld <= ap_const_logic_1;
        else 
            spike_counter_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    spike_in_valid_toggle_o_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln122_reg_687, tmp_2_reg_691, ap_enable_reg_pp0_iter0_reg, or_ln129, spike_in_valid_toggle_i, xor_ln134_fu_459_p2, ap_block_pp0_stage1_grp0)
    begin
        if (((tmp_2_reg_691 = ap_const_lv1_1) and (or_ln129 = ap_const_lv1_0) and (icmp_ln122_reg_687 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            spike_in_valid_toggle_o <= xor_ln134_fu_459_p2;
        else 
            spike_in_valid_toggle_o <= spike_in_valid_toggle_i;
        end if; 
    end process;


    spike_in_valid_toggle_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln122_reg_687, tmp_2_reg_691, ap_enable_reg_pp0_iter0_reg, or_ln129, ap_block_pp0_stage1_11001_grp0, ap_block_pp0_stage1_subdone_grp0_done_reg)
    begin
        if (((tmp_2_reg_691 = ap_const_lv1_1) and (or_ln129 = ap_const_lv1_0) and (icmp_ln122_reg_687 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            spike_in_valid_toggle_o_ap_vld <= ap_const_logic_1;
        else 
            spike_in_valid_toggle_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    spike_out_ack_toggle_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_662, grp_nbwritereq_fu_258_p9, icmp_ln122_reg_687, or_ln161, spike_out_ack_toggle_i, ap_block_pp0_stage0, xor_ln192_fu_570_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((icmp_ln122_reg_687 = ap_const_lv1_0) and (grp_nbwritereq_fu_258_p9 = ap_const_lv1_1) and (or_ln161 = ap_const_lv1_0)) or ((icmp_ln122_reg_687 = ap_const_lv1_0) and (tmp_reg_662 = ap_const_lv1_1) and (or_ln161 = ap_const_lv1_0))))) then 
            spike_out_ack_toggle_o <= xor_ln192_fu_570_p2;
        else 
            spike_out_ack_toggle_o <= spike_out_ack_toggle_i;
        end if; 
    end process;


    spike_out_ack_toggle_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_662, grp_nbwritereq_fu_258_p9, icmp_ln122_reg_687, or_ln161, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((icmp_ln122_reg_687 = ap_const_lv1_0) and (grp_nbwritereq_fu_258_p9 = ap_const_lv1_1) and (or_ln161 = ap_const_lv1_0)) or ((icmp_ln122_reg_687 = ap_const_lv1_0) and (tmp_reg_662 = ap_const_lv1_1) and (or_ln161 = ap_const_lv1_0))))) then 
            spike_out_ack_toggle_o_ap_vld <= ap_const_logic_1;
        else 
            spike_out_ack_toggle_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t_2_fu_413_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_t_1) + unsigned(ap_const_lv16_1));

    timestamp_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, timestamp_i, ap_block_pp0_stage0, tmp_1_reg_678, add_ln198_fu_592_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (tmp_1_reg_678 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            timestamp_o <= add_ln198_fu_592_p2;
        else 
            timestamp_o <= timestamp_i;
        end if; 
    end process;


    timestamp_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, tmp_1_reg_678)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (tmp_1_reg_678 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            timestamp_o_ap_vld <= ap_const_logic_1;
        else 
            timestamp_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_reg_678 <= empty_21;
    tmp_2_nbreadreq_fu_220_p9 <= (0=>(s_axis_spikes_TVALID), others=>'-');
    tmp_4_fu_498_p4 <= ((trunc_ln149_fu_494_p1 & first_spike_pending_weight_i) & zext_ln148_fu_486_p1);
    tmp_8_fu_539_p4 <= ((trunc_ln179_fu_535_p1 & spike_out_weight) & zext_ln162_cast_reg_682);
    tmp_reg_662 <= empty;
    trunc_ln136_fu_472_p1 <= s_axis_spikes_TDATA(11 - 1 downto 0);
    trunc_ln149_fu_494_p1 <= timestamp_i(11 - 1 downto 0);
    trunc_ln179_fu_535_p1 <= timestamp_i(11 - 1 downto 0);
    xor_ln134_fu_459_p2 <= (spike_in_valid_toggle_i xor ap_const_lv1_1);
    xor_ln192_fu_570_p2 <= (spike_out_ack_toggle_i xor ap_const_lv1_1);
    zext_ln148_fu_486_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(first_spike_pending_id_i),13));
    zext_ln162_cast_fu_395_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln162),13));
end behav;
