-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity snn_inference_profile_hls is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 8;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axis_spikes_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    s_axis_spikes_TVALID : IN STD_LOGIC;
    s_axis_spikes_TREADY : OUT STD_LOGIC;
    s_axis_spikes_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    s_axis_spikes_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    s_axis_spikes_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_spikes_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_spikes_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_spikes_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axis_spikes_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axis_spikes_TVALID : OUT STD_LOGIC;
    m_axis_spikes_TREADY : IN STD_LOGIC;
    m_axis_spikes_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_spikes_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_spikes_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_spikes_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_spikes_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_spikes_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    spike_in_valid : OUT STD_LOGIC_VECTOR (0 downto 0);
    spike_in_neuron_id : OUT STD_LOGIC_VECTOR (10 downto 0);
    spike_in_weight : OUT STD_LOGIC_VECTOR (7 downto 0);
    spike_in_ready : IN STD_LOGIC_VECTOR (0 downto 0);
    spike_out_valid : IN STD_LOGIC_VECTOR (0 downto 0);
    spike_out_neuron_id : IN STD_LOGIC_VECTOR (10 downto 0);
    spike_out_weight : IN STD_LOGIC_VECTOR (7 downto 0);
    spike_out_ready : OUT STD_LOGIC_VECTOR (0 downto 0);
    snn_enable : OUT STD_LOGIC_VECTOR (0 downto 0);
    snn_reset : OUT STD_LOGIC_VECTOR (0 downto 0);
    threshold_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    leak_rate_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    snn_ready : IN STD_LOGIC_VECTOR (0 downto 0);
    snn_busy : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axi_ctrl_AWVALID : IN STD_LOGIC;
    s_axi_ctrl_AWREADY : OUT STD_LOGIC;
    s_axi_ctrl_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_ctrl_WVALID : IN STD_LOGIC;
    s_axi_ctrl_WREADY : OUT STD_LOGIC;
    s_axi_ctrl_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_ctrl_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_ctrl_ARVALID : IN STD_LOGIC;
    s_axi_ctrl_ARREADY : OUT STD_LOGIC;
    s_axi_ctrl_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_ctrl_RVALID : OUT STD_LOGIC;
    s_axi_ctrl_RREADY : IN STD_LOGIC;
    s_axi_ctrl_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_ctrl_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_ctrl_BVALID : OUT STD_LOGIC;
    s_axi_ctrl_BREADY : IN STD_LOGIC;
    s_axi_ctrl_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of snn_inference_profile_hls is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "snn_inference_profile_hls_snn_inference_profile_hls,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.653000,HLS_SYN_LAT=65539,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=897,HLS_SYN_LUT=1624,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_20260221 : STD_LOGIC_VECTOR (31 downto 0) := "00100000001001100000001000100001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal ctrl_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal config_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mode_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal time_steps_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal learning_params : STD_LOGIC_VECTOR (143 downto 0);
    signal encoder_config : STD_LOGIC_VECTOR (79 downto 0);
    signal status_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal status_reg_ap_vld : STD_LOGIC;
    signal spike_count_reg_ap_vld : STD_LOGIC;
    signal weight_sum_reg_ap_vld : STD_LOGIC;
    signal version_reg_ap_vld : STD_LOGIC;
    signal reward_signal : STD_LOGIC_VECTOR (7 downto 0);
    signal timestamp : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal spike_counter : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal first_spike_sent : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal first_spike_pending : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal first_spike_pending_id : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal first_spike_pending_weight : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal spike_in_valid_toggle : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal spike_out_ack_toggle : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal snn_busy_read_reg_677 : STD_LOGIC_VECTOR (0 downto 0);
    signal snn_ready_read_reg_682 : STD_LOGIC_VECTOR (0 downto 0);
    signal spike_out_weight_read_reg_687 : STD_LOGIC_VECTOR (7 downto 0);
    signal spike_out_neuron_id_read_reg_692 : STD_LOGIC_VECTOR (10 downto 0);
    signal spike_out_valid_read_reg_698 : STD_LOGIC_VECTOR (0 downto 0);
    signal spike_in_ready_read_reg_703 : STD_LOGIC_VECTOR (0 downto 0);
    signal mode_reg_read_reg_708 : STD_LOGIC_VECTOR (31 downto 0);
    signal enable_fu_425_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal enable_reg_737 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_spike_only_reg_749 : STD_LOGIC_VECTOR (0 downto 0);
    signal time_steps_1_fu_465_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal time_steps_1_reg_756 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln129_fu_575_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln129_reg_762 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal or_ln143_fu_587_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln143_reg_767 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln161_fu_599_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln161_reg_772 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln122_fu_606_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln122_reg_777 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_done : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_idle : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_ready : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TREADY : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_s_axis_spikes_TREADY : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05525_phi_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05525_phi_out_ap_vld : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi_out_ap_vld : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi4_out : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi4_out_ap_vld : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05623_phi_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05623_phi_out_ap_vld : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_out_ack_toggle_o : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_out_ack_toggle_o_ap_vld : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_in_valid_toggle_o : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_in_valid_toggle_o_ap_vld : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_counter_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_counter_o_ap_vld : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_o : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_o_ap_vld : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_id_o : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_id_o_ap_vld : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_weight_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_weight_o_ap_vld : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_timestamp_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_timestamp_o_ap_vld : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_sent_o : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_sent_o_ap_vld : STD_LOGIC;
    signal grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal m_axis_spikes_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal m_axis_spikes_TKEEP_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal m_axis_spikes_TSTRB_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal m_axis_spikes_TUSER_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_spikes_TLAST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_spikes_TID_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_spikes_TDEST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal reset_fu_430_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal clear_counters_fu_439_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal snn_enable_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal snn_reset_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal trunc_ln119_fu_551_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal threshold_out_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal leak_rate_out_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal regslice_both_m_axis_spikes_V_data_V_U_apdone_blk : STD_LOGIC;
    signal icmp_ln87_fu_455_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal time_steps_fu_461_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal xor_ln129_fu_565_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln129_1_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln143_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln161_fu_594_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_627_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln205_fu_633_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_640_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln206_fu_637_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln206_fu_647_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal status_fu_655_p5 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal regslice_both_s_axis_spikes_V_data_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_spikes_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal s_axis_spikes_TVALID_int_regslice : STD_LOGIC;
    signal s_axis_spikes_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_s_axis_spikes_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_spikes_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_spikes_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_s_axis_spikes_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_spikes_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_spikes_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_spikes_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_s_axis_spikes_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_spikes_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_spikes_V_user_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_spikes_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_spikes_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_spikes_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_spikes_V_last_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_spikes_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_spikes_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_spikes_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_spikes_V_id_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_spikes_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_spikes_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_spikes_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_spikes_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_spikes_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_spikes_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_spikes_V_dest_V_U_ack_in : STD_LOGIC;
    signal m_axis_spikes_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal m_axis_spikes_TVALID_int_regslice : STD_LOGIC;
    signal m_axis_spikes_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_m_axis_spikes_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_spikes_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal m_axis_spikes_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_m_axis_spikes_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_spikes_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_spikes_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal m_axis_spikes_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_m_axis_spikes_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_spikes_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_spikes_V_user_V_U_apdone_blk : STD_LOGIC;
    signal m_axis_spikes_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_m_axis_spikes_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_spikes_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_spikes_V_last_V_U_apdone_blk : STD_LOGIC;
    signal m_axis_spikes_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_m_axis_spikes_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_spikes_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_spikes_V_id_V_U_apdone_blk : STD_LOGIC;
    signal m_axis_spikes_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_m_axis_spikes_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_spikes_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_spikes_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal m_axis_spikes_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_m_axis_spikes_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_spikes_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component snn_inference_profile_hls_snn_inference_profile_hls_Pipeline_TIME_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axis_spikes_TREADY : IN STD_LOGIC;
        s_axis_spikes_TVALID : IN STD_LOGIC;
        time_steps_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        empty_21 : IN STD_LOGIC_VECTOR (0 downto 0);
        or_ln161 : IN STD_LOGIC_VECTOR (0 downto 0);
        or_ln143 : IN STD_LOGIC_VECTOR (0 downto 0);
        or_ln129 : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_spikes_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        s_axis_spikes_TREADY : OUT STD_LOGIC;
        s_axis_spikes_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        s_axis_spikes_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        s_axis_spikes_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_spikes_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_spikes_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_spikes_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axis_spikes_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axis_spikes_TVALID : OUT STD_LOGIC;
        m_axis_spikes_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axis_spikes_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axis_spikes_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_spikes_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_spikes_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_spikes_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
        empty : IN STD_LOGIC_VECTOR (0 downto 0);
        spike_out_weight : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln162 : IN STD_LOGIC_VECTOR (10 downto 0);
        spike_out_neuron_id : IN STD_LOGIC_VECTOR (10 downto 0);
        p_0_0_05525_phi_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        p_0_0_05525_phi_out_ap_vld : OUT STD_LOGIC;
        p_phi_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_phi_out_ap_vld : OUT STD_LOGIC;
        p_phi4_out : OUT STD_LOGIC_VECTOR (10 downto 0);
        p_phi4_out_ap_vld : OUT STD_LOGIC;
        p_0_0_05623_phi_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        p_0_0_05623_phi_out_ap_vld : OUT STD_LOGIC;
        spike_out_ack_toggle_i : IN STD_LOGIC_VECTOR (0 downto 0);
        spike_out_ack_toggle_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        spike_out_ack_toggle_o_ap_vld : OUT STD_LOGIC;
        spike_in_valid_toggle_i : IN STD_LOGIC_VECTOR (0 downto 0);
        spike_in_valid_toggle_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        spike_in_valid_toggle_o_ap_vld : OUT STD_LOGIC;
        spike_counter_i : IN STD_LOGIC_VECTOR (31 downto 0);
        spike_counter_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        spike_counter_o_ap_vld : OUT STD_LOGIC;
        first_spike_pending_i : IN STD_LOGIC_VECTOR (0 downto 0);
        first_spike_pending_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        first_spike_pending_o_ap_vld : OUT STD_LOGIC;
        first_spike_pending_id_i : IN STD_LOGIC_VECTOR (10 downto 0);
        first_spike_pending_id_o : OUT STD_LOGIC_VECTOR (10 downto 0);
        first_spike_pending_id_o_ap_vld : OUT STD_LOGIC;
        first_spike_pending_weight_i : IN STD_LOGIC_VECTOR (7 downto 0);
        first_spike_pending_weight_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        first_spike_pending_weight_o_ap_vld : OUT STD_LOGIC;
        timestamp_i : IN STD_LOGIC_VECTOR (31 downto 0);
        timestamp_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        timestamp_o_ap_vld : OUT STD_LOGIC;
        first_spike_sent_i : IN STD_LOGIC_VECTOR (0 downto 0);
        first_spike_sent_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        first_spike_sent_o_ap_vld : OUT STD_LOGIC );
    end component;


    component snn_inference_profile_hls_ctrl_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ctrl_reg : OUT STD_LOGIC_VECTOR (31 downto 0);
        config_reg : OUT STD_LOGIC_VECTOR (31 downto 0);
        mode_reg : OUT STD_LOGIC_VECTOR (31 downto 0);
        time_steps_reg : OUT STD_LOGIC_VECTOR (31 downto 0);
        learning_params : OUT STD_LOGIC_VECTOR (143 downto 0);
        encoder_config : OUT STD_LOGIC_VECTOR (79 downto 0);
        status_reg : IN STD_LOGIC_VECTOR (31 downto 0);
        status_reg_ap_vld : IN STD_LOGIC;
        spike_count_reg : IN STD_LOGIC_VECTOR (31 downto 0);
        spike_count_reg_ap_vld : IN STD_LOGIC;
        weight_sum_reg : IN STD_LOGIC_VECTOR (31 downto 0);
        weight_sum_reg_ap_vld : IN STD_LOGIC;
        version_reg : IN STD_LOGIC_VECTOR (31 downto 0);
        version_reg_ap_vld : IN STD_LOGIC;
        reward_signal : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component snn_inference_profile_hls_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364 : component snn_inference_profile_hls_snn_inference_profile_hls_Pipeline_TIME_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start,
        ap_done => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_done,
        ap_idle => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_idle,
        ap_ready => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_ready,
        m_axis_spikes_TREADY => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TREADY,
        s_axis_spikes_TVALID => s_axis_spikes_TVALID_int_regslice,
        time_steps_1 => time_steps_1_reg_756,
        empty_21 => enable_reg_737,
        or_ln161 => or_ln161_reg_772,
        or_ln143 => or_ln143_reg_767,
        or_ln129 => or_ln129_reg_762,
        s_axis_spikes_TDATA => s_axis_spikes_TDATA_int_regslice,
        s_axis_spikes_TREADY => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_s_axis_spikes_TREADY,
        s_axis_spikes_TKEEP => s_axis_spikes_TKEEP_int_regslice,
        s_axis_spikes_TSTRB => s_axis_spikes_TSTRB_int_regslice,
        s_axis_spikes_TUSER => s_axis_spikes_TUSER_int_regslice,
        s_axis_spikes_TLAST => s_axis_spikes_TLAST_int_regslice,
        s_axis_spikes_TID => s_axis_spikes_TID_int_regslice,
        s_axis_spikes_TDEST => s_axis_spikes_TDEST_int_regslice,
        m_axis_spikes_TDATA => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDATA,
        m_axis_spikes_TVALID => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID,
        m_axis_spikes_TKEEP => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TKEEP,
        m_axis_spikes_TSTRB => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TSTRB,
        m_axis_spikes_TUSER => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TUSER,
        m_axis_spikes_TLAST => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TLAST,
        m_axis_spikes_TID => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TID,
        m_axis_spikes_TDEST => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDEST,
        empty => first_spike_only_reg_749,
        spike_out_weight => spike_out_weight_read_reg_687,
        zext_ln162 => spike_out_neuron_id_read_reg_692,
        spike_out_neuron_id => spike_out_neuron_id_read_reg_692,
        p_0_0_05525_phi_out => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05525_phi_out,
        p_0_0_05525_phi_out_ap_vld => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05525_phi_out_ap_vld,
        p_phi_out => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi_out,
        p_phi_out_ap_vld => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi_out_ap_vld,
        p_phi4_out => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi4_out,
        p_phi4_out_ap_vld => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi4_out_ap_vld,
        p_0_0_05623_phi_out => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05623_phi_out,
        p_0_0_05623_phi_out_ap_vld => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05623_phi_out_ap_vld,
        spike_out_ack_toggle_i => spike_out_ack_toggle,
        spike_out_ack_toggle_o => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_out_ack_toggle_o,
        spike_out_ack_toggle_o_ap_vld => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_out_ack_toggle_o_ap_vld,
        spike_in_valid_toggle_i => spike_in_valid_toggle,
        spike_in_valid_toggle_o => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_in_valid_toggle_o,
        spike_in_valid_toggle_o_ap_vld => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_in_valid_toggle_o_ap_vld,
        spike_counter_i => spike_counter,
        spike_counter_o => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_counter_o,
        spike_counter_o_ap_vld => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_counter_o_ap_vld,
        first_spike_pending_i => first_spike_pending,
        first_spike_pending_o => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_o,
        first_spike_pending_o_ap_vld => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_o_ap_vld,
        first_spike_pending_id_i => first_spike_pending_id,
        first_spike_pending_id_o => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_id_o,
        first_spike_pending_id_o_ap_vld => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_id_o_ap_vld,
        first_spike_pending_weight_i => first_spike_pending_weight,
        first_spike_pending_weight_o => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_weight_o,
        first_spike_pending_weight_o_ap_vld => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_weight_o_ap_vld,
        timestamp_i => timestamp,
        timestamp_o => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_timestamp_o,
        timestamp_o_ap_vld => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_timestamp_o_ap_vld,
        first_spike_sent_i => first_spike_sent,
        first_spike_sent_o => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_sent_o,
        first_spike_sent_o_ap_vld => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_sent_o_ap_vld);

    ctrl_s_axi_U : component snn_inference_profile_hls_ctrl_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_ctrl_AWVALID,
        AWREADY => s_axi_ctrl_AWREADY,
        AWADDR => s_axi_ctrl_AWADDR,
        WVALID => s_axi_ctrl_WVALID,
        WREADY => s_axi_ctrl_WREADY,
        WDATA => s_axi_ctrl_WDATA,
        WSTRB => s_axi_ctrl_WSTRB,
        ARVALID => s_axi_ctrl_ARVALID,
        ARREADY => s_axi_ctrl_ARREADY,
        ARADDR => s_axi_ctrl_ARADDR,
        RVALID => s_axi_ctrl_RVALID,
        RREADY => s_axi_ctrl_RREADY,
        RDATA => s_axi_ctrl_RDATA,
        RRESP => s_axi_ctrl_RRESP,
        BVALID => s_axi_ctrl_BVALID,
        BREADY => s_axi_ctrl_BREADY,
        BRESP => s_axi_ctrl_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ctrl_reg => ctrl_reg,
        config_reg => config_reg,
        mode_reg => mode_reg,
        time_steps_reg => time_steps_reg,
        learning_params => learning_params,
        encoder_config => encoder_config,
        status_reg => status_reg,
        status_reg_ap_vld => status_reg_ap_vld,
        spike_count_reg => spike_counter,
        spike_count_reg_ap_vld => spike_count_reg_ap_vld,
        weight_sum_reg => ap_const_lv32_0,
        weight_sum_reg_ap_vld => weight_sum_reg_ap_vld,
        version_reg => ap_const_lv32_20260221,
        version_reg_ap_vld => version_reg_ap_vld,
        reward_signal => reward_signal,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    regslice_both_s_axis_spikes_V_data_V_U : component snn_inference_profile_hls_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_spikes_TDATA,
        vld_in => s_axis_spikes_TVALID,
        ack_in => regslice_both_s_axis_spikes_V_data_V_U_ack_in,
        data_out => s_axis_spikes_TDATA_int_regslice,
        vld_out => s_axis_spikes_TVALID_int_regslice,
        ack_out => s_axis_spikes_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_spikes_V_data_V_U_apdone_blk);

    regslice_both_s_axis_spikes_V_keep_V_U : component snn_inference_profile_hls_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_spikes_TKEEP,
        vld_in => s_axis_spikes_TVALID,
        ack_in => regslice_both_s_axis_spikes_V_keep_V_U_ack_in,
        data_out => s_axis_spikes_TKEEP_int_regslice,
        vld_out => regslice_both_s_axis_spikes_V_keep_V_U_vld_out,
        ack_out => s_axis_spikes_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_spikes_V_keep_V_U_apdone_blk);

    regslice_both_s_axis_spikes_V_strb_V_U : component snn_inference_profile_hls_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_spikes_TSTRB,
        vld_in => s_axis_spikes_TVALID,
        ack_in => regslice_both_s_axis_spikes_V_strb_V_U_ack_in,
        data_out => s_axis_spikes_TSTRB_int_regslice,
        vld_out => regslice_both_s_axis_spikes_V_strb_V_U_vld_out,
        ack_out => s_axis_spikes_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_spikes_V_strb_V_U_apdone_blk);

    regslice_both_s_axis_spikes_V_user_V_U : component snn_inference_profile_hls_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_spikes_TUSER,
        vld_in => s_axis_spikes_TVALID,
        ack_in => regslice_both_s_axis_spikes_V_user_V_U_ack_in,
        data_out => s_axis_spikes_TUSER_int_regslice,
        vld_out => regslice_both_s_axis_spikes_V_user_V_U_vld_out,
        ack_out => s_axis_spikes_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_spikes_V_user_V_U_apdone_blk);

    regslice_both_s_axis_spikes_V_last_V_U : component snn_inference_profile_hls_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_spikes_TLAST,
        vld_in => s_axis_spikes_TVALID,
        ack_in => regslice_both_s_axis_spikes_V_last_V_U_ack_in,
        data_out => s_axis_spikes_TLAST_int_regslice,
        vld_out => regslice_both_s_axis_spikes_V_last_V_U_vld_out,
        ack_out => s_axis_spikes_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_spikes_V_last_V_U_apdone_blk);

    regslice_both_s_axis_spikes_V_id_V_U : component snn_inference_profile_hls_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_spikes_TID,
        vld_in => s_axis_spikes_TVALID,
        ack_in => regslice_both_s_axis_spikes_V_id_V_U_ack_in,
        data_out => s_axis_spikes_TID_int_regslice,
        vld_out => regslice_both_s_axis_spikes_V_id_V_U_vld_out,
        ack_out => s_axis_spikes_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_spikes_V_id_V_U_apdone_blk);

    regslice_both_s_axis_spikes_V_dest_V_U : component snn_inference_profile_hls_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_spikes_TDEST,
        vld_in => s_axis_spikes_TVALID,
        ack_in => regslice_both_s_axis_spikes_V_dest_V_U_ack_in,
        data_out => s_axis_spikes_TDEST_int_regslice,
        vld_out => regslice_both_s_axis_spikes_V_dest_V_U_vld_out,
        ack_out => s_axis_spikes_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_spikes_V_dest_V_U_apdone_blk);

    regslice_both_m_axis_spikes_V_data_V_U : component snn_inference_profile_hls_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_spikes_TDATA_int_regslice,
        vld_in => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID,
        ack_in => m_axis_spikes_TREADY_int_regslice,
        data_out => m_axis_spikes_TDATA,
        vld_out => regslice_both_m_axis_spikes_V_data_V_U_vld_out,
        ack_out => m_axis_spikes_TREADY,
        apdone_blk => regslice_both_m_axis_spikes_V_data_V_U_apdone_blk);

    regslice_both_m_axis_spikes_V_keep_V_U : component snn_inference_profile_hls_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_spikes_TKEEP_int_regslice,
        vld_in => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID,
        ack_in => regslice_both_m_axis_spikes_V_keep_V_U_ack_in_dummy,
        data_out => m_axis_spikes_TKEEP,
        vld_out => regslice_both_m_axis_spikes_V_keep_V_U_vld_out,
        ack_out => m_axis_spikes_TREADY,
        apdone_blk => regslice_both_m_axis_spikes_V_keep_V_U_apdone_blk);

    regslice_both_m_axis_spikes_V_strb_V_U : component snn_inference_profile_hls_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_spikes_TSTRB_int_regslice,
        vld_in => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID,
        ack_in => regslice_both_m_axis_spikes_V_strb_V_U_ack_in_dummy,
        data_out => m_axis_spikes_TSTRB,
        vld_out => regslice_both_m_axis_spikes_V_strb_V_U_vld_out,
        ack_out => m_axis_spikes_TREADY,
        apdone_blk => regslice_both_m_axis_spikes_V_strb_V_U_apdone_blk);

    regslice_both_m_axis_spikes_V_user_V_U : component snn_inference_profile_hls_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_spikes_TUSER_int_regslice,
        vld_in => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID,
        ack_in => regslice_both_m_axis_spikes_V_user_V_U_ack_in_dummy,
        data_out => m_axis_spikes_TUSER,
        vld_out => regslice_both_m_axis_spikes_V_user_V_U_vld_out,
        ack_out => m_axis_spikes_TREADY,
        apdone_blk => regslice_both_m_axis_spikes_V_user_V_U_apdone_blk);

    regslice_both_m_axis_spikes_V_last_V_U : component snn_inference_profile_hls_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_spikes_TLAST_int_regslice,
        vld_in => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID,
        ack_in => regslice_both_m_axis_spikes_V_last_V_U_ack_in_dummy,
        data_out => m_axis_spikes_TLAST,
        vld_out => regslice_both_m_axis_spikes_V_last_V_U_vld_out,
        ack_out => m_axis_spikes_TREADY,
        apdone_blk => regslice_both_m_axis_spikes_V_last_V_U_apdone_blk);

    regslice_both_m_axis_spikes_V_id_V_U : component snn_inference_profile_hls_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_spikes_TID_int_regslice,
        vld_in => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID,
        ack_in => regslice_both_m_axis_spikes_V_id_V_U_ack_in_dummy,
        data_out => m_axis_spikes_TID,
        vld_out => regslice_both_m_axis_spikes_V_id_V_U_vld_out,
        ack_out => m_axis_spikes_TREADY,
        apdone_blk => regslice_both_m_axis_spikes_V_id_V_U_apdone_blk);

    regslice_both_m_axis_spikes_V_dest_V_U : component snn_inference_profile_hls_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_spikes_TDEST_int_regslice,
        vld_in => grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID,
        ack_in => regslice_both_m_axis_spikes_V_dest_V_U_ack_in_dummy,
        data_out => m_axis_spikes_TDEST,
        vld_out => regslice_both_m_axis_spikes_V_dest_V_U_vld_out,
        ack_out => m_axis_spikes_TREADY,
        apdone_blk => regslice_both_m_axis_spikes_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_ready = ap_const_logic_1)) then 
                    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    leak_rate_out_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                leak_rate_out_preg <= ap_const_lv16_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    leak_rate_out_preg <= config_reg(31 downto 16);
                end if; 
            end if;
        end if;
    end process;


    snn_enable_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                snn_enable_preg <= ap_const_lv1_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    snn_enable_preg <= enable_fu_425_p1;
                end if; 
            end if;
        end if;
    end process;


    snn_reset_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                snn_reset_preg <= ap_const_lv1_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    snn_reset_preg <= ctrl_reg(1 downto 1);
                end if; 
            end if;
        end if;
    end process;


    threshold_out_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                threshold_out_preg <= ap_const_lv16_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    threshold_out_preg <= trunc_ln119_fu_551_p1;
                end if; 
            end if;
        end if;
    end process;


    first_spike_pending_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((enable_fu_425_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)) or ((reset_fu_430_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
                first_spike_pending <= ap_const_lv1_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_o_ap_vld = ap_const_logic_1))) then 
                first_spike_pending <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_o;
            end if; 
        end if;
    end process;

    first_spike_pending_id_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((enable_fu_425_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)) or ((reset_fu_430_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
                first_spike_pending_id <= ap_const_lv11_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_id_o_ap_vld = ap_const_logic_1))) then 
                first_spike_pending_id <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_id_o;
            end if; 
        end if;
    end process;

    first_spike_pending_weight_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((enable_fu_425_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)) or ((reset_fu_430_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
                first_spike_pending_weight <= ap_const_lv8_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_weight_o_ap_vld = ap_const_logic_1))) then 
                first_spike_pending_weight <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_pending_weight_o;
            end if; 
        end if;
    end process;

    first_spike_sent_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((enable_fu_425_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)) or ((reset_fu_430_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
                first_spike_sent <= ap_const_lv1_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_sent_o_ap_vld = ap_const_logic_1))) then 
                first_spike_sent <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_first_spike_sent_o;
            end if; 
        end if;
    end process;

    spike_counter_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((clear_counters_fu_439_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)) or ((reset_fu_430_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
                spike_counter <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_counter_o_ap_vld = ap_const_logic_1))) then 
                spike_counter <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_counter_o;
            end if; 
        end if;
    end process;

    spike_in_valid_toggle_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((reset_fu_430_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                spike_in_valid_toggle <= ap_const_lv1_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_in_valid_toggle_o_ap_vld = ap_const_logic_1))) then 
                spike_in_valid_toggle <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_in_valid_toggle_o;
            end if; 
        end if;
    end process;

    spike_out_ack_toggle_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((reset_fu_430_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                spike_out_ack_toggle <= ap_const_lv1_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_out_ack_toggle_o_ap_vld = ap_const_logic_1))) then 
                spike_out_ack_toggle <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_spike_out_ack_toggle_o;
            end if; 
        end if;
    end process;

    timestamp_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((reset_fu_430_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                timestamp <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_timestamp_o_ap_vld = ap_const_logic_1))) then 
                timestamp <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_timestamp_o;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                enable_reg_737 <= enable_fu_425_p1;
                first_spike_only_reg_749 <= ctrl_reg(7 downto 7);
                mode_reg_read_reg_708 <= mode_reg;
                snn_busy_read_reg_677 <= snn_busy;
                snn_ready_read_reg_682 <= snn_ready;
                spike_in_ready_read_reg_703 <= spike_in_ready;
                spike_out_neuron_id_read_reg_692 <= spike_out_neuron_id;
                spike_out_valid_read_reg_698 <= spike_out_valid;
                spike_out_weight_read_reg_687 <= spike_out_weight;
                time_steps_1_reg_756 <= time_steps_1_fu_465_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                icmp_ln122_reg_777 <= icmp_ln122_fu_606_p2;
                or_ln129_reg_762 <= or_ln129_fu_575_p2;
                or_ln143_reg_767 <= or_ln143_fu_587_p2;
                or_ln161_reg_772 <= or_ln161_fu_599_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID = ap_const_logic_1))) then
                m_axis_spikes_TDATA_reg <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDATA;
                m_axis_spikes_TDEST_reg <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDEST;
                m_axis_spikes_TID_reg <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TID;
                m_axis_spikes_TKEEP_reg <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TKEEP;
                m_axis_spikes_TLAST_reg <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TLAST;
                m_axis_spikes_TSTRB_reg <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TSTRB;
                m_axis_spikes_TUSER_reg <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TUSER;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state4, regslice_both_m_axis_spikes_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((regslice_both_m_axis_spikes_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_done)
    begin
        if ((grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(regslice_both_m_axis_spikes_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_m_axis_spikes_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state4, regslice_both_m_axis_spikes_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_m_axis_spikes_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4, regslice_both_m_axis_spikes_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_m_axis_spikes_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    clear_counters_fu_439_p3 <= ctrl_reg(2 downto 2);
    enable_fu_425_p1 <= ctrl_reg(1 - 1 downto 0);
    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_ap_start_reg;
    grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TREADY <= (m_axis_spikes_TREADY_int_regslice and ap_CS_fsm_state3);
    icmp_ln122_fu_606_p2 <= "1" when (time_steps_1_reg_756 = ap_const_lv16_0) else "0";
    icmp_ln87_fu_455_p2 <= "1" when (time_steps_reg = ap_const_lv32_0) else "0";

    leak_rate_out_assign_proc : process(ap_start, ap_CS_fsm_state1, config_reg, leak_rate_out_preg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            leak_rate_out <= config_reg(31 downto 16);
        else 
            leak_rate_out <= leak_rate_out_preg;
        end if; 
    end process;


    m_axis_spikes_TDATA_int_regslice_assign_proc : process(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDATA, grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID, ap_CS_fsm_state3, m_axis_spikes_TDATA_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID = ap_const_logic_1))) then 
            m_axis_spikes_TDATA_int_regslice <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDATA;
        else 
            m_axis_spikes_TDATA_int_regslice <= m_axis_spikes_TDATA_reg;
        end if; 
    end process;


    m_axis_spikes_TDEST_int_regslice_assign_proc : process(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID, grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDEST, ap_CS_fsm_state3, m_axis_spikes_TDEST_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID = ap_const_logic_1))) then 
            m_axis_spikes_TDEST_int_regslice <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TDEST;
        else 
            m_axis_spikes_TDEST_int_regslice <= m_axis_spikes_TDEST_reg;
        end if; 
    end process;


    m_axis_spikes_TID_int_regslice_assign_proc : process(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID, grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TID, ap_CS_fsm_state3, m_axis_spikes_TID_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID = ap_const_logic_1))) then 
            m_axis_spikes_TID_int_regslice <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TID;
        else 
            m_axis_spikes_TID_int_regslice <= m_axis_spikes_TID_reg;
        end if; 
    end process;


    m_axis_spikes_TKEEP_int_regslice_assign_proc : process(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID, grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TKEEP, ap_CS_fsm_state3, m_axis_spikes_TKEEP_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID = ap_const_logic_1))) then 
            m_axis_spikes_TKEEP_int_regslice <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TKEEP;
        else 
            m_axis_spikes_TKEEP_int_regslice <= m_axis_spikes_TKEEP_reg;
        end if; 
    end process;


    m_axis_spikes_TLAST_int_regslice_assign_proc : process(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID, grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TLAST, ap_CS_fsm_state3, m_axis_spikes_TLAST_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID = ap_const_logic_1))) then 
            m_axis_spikes_TLAST_int_regslice <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TLAST;
        else 
            m_axis_spikes_TLAST_int_regslice <= m_axis_spikes_TLAST_reg;
        end if; 
    end process;


    m_axis_spikes_TSTRB_int_regslice_assign_proc : process(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID, grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TSTRB, ap_CS_fsm_state3, m_axis_spikes_TSTRB_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID = ap_const_logic_1))) then 
            m_axis_spikes_TSTRB_int_regslice <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TSTRB;
        else 
            m_axis_spikes_TSTRB_int_regslice <= m_axis_spikes_TSTRB_reg;
        end if; 
    end process;


    m_axis_spikes_TUSER_int_regslice_assign_proc : process(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID, grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TUSER, ap_CS_fsm_state3, m_axis_spikes_TUSER_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID = ap_const_logic_1))) then 
            m_axis_spikes_TUSER_int_regslice <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TUSER;
        else 
            m_axis_spikes_TUSER_int_regslice <= m_axis_spikes_TUSER_reg;
        end if; 
    end process;

    m_axis_spikes_TVALID <= regslice_both_m_axis_spikes_V_data_V_U_vld_out;
    m_axis_spikes_TVALID_int_regslice <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_m_axis_spikes_TVALID;
    or_ln129_fu_575_p2 <= (xor_ln129_fu_565_p2 or xor_ln129_1_fu_570_p2);
    or_ln143_fu_587_p2 <= (xor_ln143_fu_582_p2 or xor_ln129_fu_565_p2);
    or_ln161_fu_599_p2 <= (xor_ln161_fu_594_p2 or xor_ln129_fu_565_p2);
    reset_fu_430_p3 <= ctrl_reg(1 downto 1);
    s_axis_spikes_TREADY <= regslice_both_s_axis_spikes_V_data_V_U_ack_in;

    s_axis_spikes_TREADY_int_regslice_assign_proc : process(grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_s_axis_spikes_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            s_axis_spikes_TREADY_int_regslice <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_s_axis_spikes_TREADY;
        else 
            s_axis_spikes_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    snn_enable_assign_proc : process(ap_start, ap_CS_fsm_state1, enable_fu_425_p1, snn_enable_preg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            snn_enable <= enable_fu_425_p1;
        else 
            snn_enable <= snn_enable_preg;
        end if; 
    end process;


    snn_reset_assign_proc : process(ap_start, ap_CS_fsm_state1, ctrl_reg, snn_reset_preg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            snn_reset <= ctrl_reg(1 downto 1);
        else 
            snn_reset <= snn_reset_preg;
        end if; 
    end process;


    spike_count_reg_ap_vld_assign_proc : process(ap_CS_fsm_state4, regslice_both_m_axis_spikes_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_m_axis_spikes_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            spike_count_reg_ap_vld <= ap_const_logic_1;
        else 
            spike_count_reg_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    spike_in_neuron_id <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi4_out;
    spike_in_valid <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05623_phi_out;
    spike_in_weight <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_phi_out;
    spike_out_ready <= grp_snn_inference_profile_hls_Pipeline_TIME_LOOP_fu_364_p_0_0_05525_phi_out;
    status_fu_655_p5 <= (((first_spike_pending & ap_const_lv8_0) & trunc_ln206_fu_637_p1) & zext_ln206_fu_647_p1);
    status_reg <= std_logic_vector(IEEE.numeric_std.resize(unsigned(status_fu_655_p5),32));

    status_reg_ap_vld_assign_proc : process(ap_CS_fsm_state4, regslice_both_m_axis_spikes_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_m_axis_spikes_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            status_reg_ap_vld <= ap_const_logic_1;
        else 
            status_reg_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    threshold_out_assign_proc : process(ap_start, ap_CS_fsm_state1, trunc_ln119_fu_551_p1, threshold_out_preg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            threshold_out <= trunc_ln119_fu_551_p1;
        else 
            threshold_out <= threshold_out_preg;
        end if; 
    end process;

    time_steps_1_fu_465_p3 <= 
        ap_const_lv16_1 when (icmp_ln87_fu_455_p2(0) = '1') else 
        time_steps_fu_461_p1;
    time_steps_fu_461_p1 <= time_steps_reg(16 - 1 downto 0);
    tmp_9_fu_627_p3 <= (snn_busy_read_reg_677 & snn_ready_read_reg_682);
    tmp_s_fu_640_p3 <= (first_spike_only_reg_749 & zext_ln205_fu_633_p1);
    trunc_ln119_fu_551_p1 <= config_reg(16 - 1 downto 0);
    trunc_ln206_fu_637_p1 <= mode_reg_read_reg_708(2 - 1 downto 0);

    version_reg_ap_vld_assign_proc : process(ap_CS_fsm_state4, regslice_both_m_axis_spikes_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_m_axis_spikes_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            version_reg_ap_vld <= ap_const_logic_1;
        else 
            version_reg_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    weight_sum_reg_ap_vld_assign_proc : process(ap_CS_fsm_state4, regslice_both_m_axis_spikes_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_m_axis_spikes_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            weight_sum_reg_ap_vld <= ap_const_logic_1;
        else 
            weight_sum_reg_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln129_1_fu_570_p2 <= (spike_in_ready_read_reg_703 xor ap_const_lv1_1);
    xor_ln129_fu_565_p2 <= (enable_reg_737 xor ap_const_lv1_1);
    xor_ln143_fu_582_p2 <= (first_spike_only_reg_749 xor ap_const_lv1_1);
    xor_ln161_fu_594_p2 <= (spike_out_valid_read_reg_698 xor ap_const_lv1_1);
    zext_ln205_fu_633_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_627_p3),3));
    zext_ln206_fu_647_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_640_p3),6));
end behav;
